/**
 * Determinism, and the reason it is not optional.
 *
 * The whole estate is regenerated by one command. If that command produces
 * different rows each time then every trap has to be re-found by hand after
 * every run, the acceptance cases stop being derivable, and `db:check` becomes
 * a test of today's dice rather than of the design. So: a seeded PRNG, a fixed
 * epoch, and NO `Date.now()`, `Math.random()` or `new Date()` anywhere below
 * this file. Same seed in, byte-identical world out.
 *
 * ONE DELIBERATE DEPARTURE FROM PHARMA, AND IT IS THE LESSON PHARMA LEARNED.
 * There, `buildWorld()` makes one `makeHelpers(SEED)` and every later generator
 * destructures the SAME `h` — so a new generator that draws even one number
 * shifts every value produced after it, and
 * `apps/ai/pharma/src/db/seed/world-fingerprint.ts` exists to catch exactly
 * that. Here every builder gets its OWN stream from the start
 * (`makeHelpers(SEED + STREAM.x)`), which is the fix that file recommends,
 * applied before the problem rather than after it. Adding a sixth builder
 * cannot disturb the five that exist. The fingerprint is still worth having —
 * it catches a builder that changes its own output — but it should now only
 * ever report the table somebody actually edited.
 */

/** mulberry32 — small, fast, good enough, and identical across Node versions. */
export type Rand = () => number;

export function rng(seed: number): Rand {
  let a = seed >>> 0;
  return function next() {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** The one seed the estate comes off. */
export const SEED = 20260918;

/**
 * One offset per builder, so no two share a stream. Named rather than numbered
 * at the call site because `makeHelpers(SEED + 3)` tells a reader nothing.
 */
export const STREAM = {
  policy: 11,
  shop: 23,
  warehouse: 37,
  fleet: 53,
  contact: 71,
} as const;

/**
 * TODAY, frozen. Every relative date in the world is computed from this.
 *
 * CHOSEN FOR TRAP T6 AND NOT ARBITRARILY. Orders run back 120 days from here,
 * which is 2026-05-21 → 2026-09-18, and that span has to CONTAIN a bank holiday
 * or `bank_holidays` is a table with nothing to catch. It contains two: the
 * spring holiday on Mon 2026-05-25 and — the one T6 uses — the England & Wales
 * summer holiday on Mon 2026-08-31, comfortably inside the range rather than at
 * its edge, so the SLA windows that straddle it have room on both sides.
 */
export const EPOCH = new Date(Date.UTC(2026, 8, 18)); // 2026-09-18, a Friday

export interface Helpers {
  r: Rand;
  /** Inclusive on both ends. */
  int(lo: number, hi: number): number;
  pick<T>(arr: readonly T[]): T;
  chance(p: number): boolean;
  shuffle<T>(arr: readonly T[]): T[];
}

export function makeHelpers(seed: number): Helpers {
  const r = rng(seed);
  const int = (lo: number, hi: number) => lo + Math.floor(r() * (hi - lo + 1));
  const pick = <T,>(arr: readonly T[]): T => arr[Math.floor(r() * arr.length)];
  const chance = (p: number) => r() < p;
  /** Shuffle a copy. Fisher-Yates off the same stream, so it stays deterministic. */
  const shuffle = <T,>(arr: readonly T[]): T[] => {
    const a = [...arr];
    for (let i = a.length - 1; i > 0; i--) {
      const j = Math.floor(r() * (i + 1));
      [a[i], a[j]] = [a[j], a[i]];
    }
    return a;
  };
  return { r, int, pick, chance, shuffle };
}

// ---------------------------------------------------------------- dates ----

export function addDays(d: Date, n: number): Date {
  const out = new Date(d.getTime());
  out.setUTCDate(out.getUTCDate() + n);
  return out;
}

/** Add whole hours. Every timestamp in the seed is built this way, never parsed. */
export function addHours(d: Date, n: number): Date {
  return new Date(d.getTime() + n * 3600_000);
}

/** `YYYY-MM-DD`. Postgres `date` columns want this and nothing else. */
export function iso(d: Date): string {
  return d.toISOString().slice(0, 10);
}

/** Full timestamp, UTC. */
export function ts(d: Date): string {
  return d.toISOString();
}

/** Zero-padded id helper: `pad('ORD-', 1421, 6)` → `ORD-001421`. */
export function pad(prefix: string, n: number, width: number): string {
  return `${prefix}${String(n).padStart(width, '0')}`;
}
