/**
 * Determinism, and the reason it is not optional.
 *
 * The whole estate is regenerated by one command. If that command produces
 * different rows each time, then every trap has to be re-found by hand after
 * every run, the acceptance case stops being derivable, and `db:check` becomes
 * a test of today's dice rather than of the design. So: a seeded PRNG, a fixed
 * epoch, and NO `Date.now()`, `Math.random()` or `new Date()` anywhere below
 * this file. Same seed in, byte-identical world out.
 *
 * `packages/insurance/scripts/corpus/` already has this property for documents
 * and it is the reason that corpus can be regenerated without fear. Same rule,
 * different data.
 */

/** mulberry32 — small, fast, good enough, and identical across Node versions. */
export type Rand = () => number;

export function rng(seed: number): Rand {
  let a = seed >>> 0;
  return function next() {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/**
 * TODAY, frozen.
 *
 * Every relative date in the world is computed from this constant. The plan's
 * acceptance case pins a certification on 2026-09-04 and a training expiry on
 * 2026-08-24; those only stay eleven days apart if "now" never moves.
 */
export const EPOCH = new Date(Date.UTC(2026, 8, 11)); // 2026-09-11

export interface Helpers {
  r: Rand;
  /** Inclusive on both ends. */
  int(lo: number, hi: number): number;
  pick<T>(arr: readonly T[]): T;
  chance(p: number): boolean;
  num(lo: number, hi: number, dp?: number): number;
  shuffle<T>(arr: readonly T[]): T[];
}

export function makeHelpers(seed: number): Helpers {
  const r = rng(seed);

  const int = (lo: number, hi: number) => lo + Math.floor(r() * (hi - lo + 1));
  const pick = <T,>(arr: readonly T[]): T => arr[Math.floor(r() * arr.length)];
  const chance = (p: number) => r() < p;
  /** A number in [lo, hi] rounded to `dp` places. */
  const num = (lo: number, hi: number, dp = 2) => Number((lo + r() * (hi - lo)).toFixed(dp));
  /** Shuffle a copy. Fisher-Yates off the same stream, so it stays deterministic. */
  const shuffle = <T,>(arr: readonly T[]): T[] => {
    const a = [...arr];
    for (let i = a.length - 1; i > 0; i--) {
      const j = Math.floor(r() * (i + 1));
      [a[i], a[j]] = [a[j], a[i]];
    }
    return a;
  };

  return { r, int, pick, chance, num, shuffle };
}

// ---------------------------------------------------------------- dates ----

export function addDays(d: Date, n: number): Date {
  const out = new Date(d.getTime());
  out.setUTCDate(out.getUTCDate() + n);
  return out;
}

export function addMonths(d: Date, n: number): Date {
  const out = new Date(d.getTime());
  out.setUTCMonth(out.getUTCMonth() + n);
  return out;
}

/** `YYYY-MM-DD`. Postgres `date` columns want this and nothing else. */
export function iso(d: Date): string {
  return d.toISOString().slice(0, 10);
}

/** Full timestamp, UTC. */
export function ts(d: Date): string {
  return d.toISOString();
}

/** `YYMM` — the campaign segment of a lot code. */
export function campaignOf(d: Date): string {
  const yy = String(d.getUTCFullYear()).slice(2);
  const mm = String(d.getUTCMonth() + 1).padStart(2, '0');
  return `${yy}${mm}`;
}

/** Zero-padded id helper: `pad('EMP-', 142, 4)` → `EMP-0142`. */
export function pad(prefix: string, n: number, width: number): string {
  return `${prefix}${String(n).padStart(width, '0')}`;
}
