/**
 * GENERATED by `node scripts/arch-graph.mjs` — do not edit.
 *
 * The repo's real package graph, read from every `package.json` and the three
 * globs in `pnpm-workspace.yaml`. Regenerate with `pnpm arch:graph`; assert it
 * is current with `pnpm arch:check`.
 *
 * WHAT THIS FILE DOES NOT CONTAIN is what any of it means — which file handles
 * which stage of a request, and why. That is written by hand in
 * `pages/learn/Architecture.tsx`, because it is not derivable from a manifest
 * and a generated sentence about a package would be a plausible one rather than
 * a true one.
 */
export interface ArchPackage {
  name: string;
  /** Path from the repo root. */
  dir: string;
  /** Which workspace glob it came from — the layer it lives in. */
  glob: string;
  kind: 'shared' | 'provider' | 'judgement' | 'surface';
  /** Lines of .ts/.tsx under src/. A weak measure; the page says so. */
  lines: number;
  /** Workspace dependencies only — the edges of the graph. */
  deps: string[];
  /** How many third-party dependencies. Counted, not listed. */
  external: number;
}

export const GENERATED_AT = "2026-09-15";

export const PACKAGES: ArchPackage[] = [
  {
    "name": "@claims/insurance",
    "dir": "apps/ai/insurance",
    "glob": "apps/ai/*",
    "kind": "judgement",
    "lines": 2999,
    "deps": [
      "@fde/grounding",
      "@fde/evals",
      "@fde/schema",
      "@fde/agent",
      "@fde/telemetry",
      "@fde/foundry",
      "@fde/guard"
    ],
    "external": 22
  },
  {
    "name": "@claims/insurance-app",
    "dir": "apps/web/insurance-app",
    "glob": "apps/web/*",
    "kind": "surface",
    "lines": 1161,
    "deps": [
      "@claims/insurance",
      "@fde/guard",
      "@fde/uikit"
    ],
    "external": 5
  },
  {
    "name": "@fde/agent",
    "dir": "packages/agent",
    "glob": "packages/*",
    "kind": "shared",
    "lines": 3508,
    "deps": [
      "@fde/foundry"
    ],
    "external": 12
  },
  {
    "name": "@fde/bedrock",
    "dir": "packages/providers/bedrock",
    "glob": "packages/providers/*",
    "kind": "provider",
    "lines": 571,
    "deps": [],
    "external": 2
  },
  {
    "name": "@fde/estate",
    "dir": "packages/estate",
    "glob": "packages/*",
    "kind": "shared",
    "lines": 406,
    "deps": [],
    "external": 1
  },
  {
    "name": "@fde/evals",
    "dir": "packages/evals",
    "glob": "packages/*",
    "kind": "shared",
    "lines": 2084,
    "deps": [],
    "external": 7
  },
  {
    "name": "@fde/foundry",
    "dir": "packages/providers/foundry",
    "glob": "packages/providers/*",
    "kind": "provider",
    "lines": 94,
    "deps": [],
    "external": 2
  },
  {
    "name": "@fde/grounding",
    "dir": "packages/grounding",
    "glob": "packages/*",
    "kind": "shared",
    "lines": 3405,
    "deps": [],
    "external": 5
  },
  {
    "name": "@fde/guard",
    "dir": "packages/guard",
    "glob": "packages/*",
    "kind": "shared",
    "lines": 349,
    "deps": [],
    "external": 0
  },
  {
    "name": "@fde/scanner",
    "dir": "packages/scanner",
    "glob": "packages/*",
    "kind": "shared",
    "lines": 299,
    "deps": [],
    "external": 0
  },
  {
    "name": "@fde/schema",
    "dir": "packages/schema",
    "glob": "packages/*",
    "kind": "shared",
    "lines": 304,
    "deps": [],
    "external": 1
  },
  {
    "name": "@fde/telemetry",
    "dir": "packages/telemetry",
    "glob": "packages/*",
    "kind": "shared",
    "lines": 540,
    "deps": [],
    "external": 1
  },
  {
    "name": "@fde/uikit",
    "dir": "packages/uikit",
    "glob": "packages/*",
    "kind": "shared",
    "lines": 2115,
    "deps": [],
    "external": 0
  },
  {
    "name": "@meridian/pharma",
    "dir": "apps/ai/pharma",
    "glob": "apps/ai/*",
    "kind": "judgement",
    "lines": 16634,
    "deps": [
      "@fde/agent",
      "@fde/estate",
      "@fde/evals",
      "@fde/foundry",
      "@fde/grounding",
      "@fde/scanner",
      "@fde/schema",
      "@fde/telemetry"
    ],
    "external": 6
  },
  {
    "name": "@meridian/pharma-app",
    "dir": "apps/web/pharma-app",
    "glob": "apps/web/*",
    "kind": "surface",
    "lines": 8134,
    "deps": [
      "@fde/guard",
      "@fde/uikit",
      "@meridian/pharma",
      "@veresk/surface"
    ],
    "external": 6
  },
  {
    "name": "@vantis/steering",
    "dir": "apps/ai/steering",
    "glob": "apps/ai/*",
    "kind": "judgement",
    "lines": 21470,
    "deps": [
      "@fde/agent",
      "@fde/bedrock",
      "@fde/estate",
      "@fde/evals",
      "@fde/foundry",
      "@fde/grounding",
      "@fde/schema",
      "@fde/telemetry"
    ],
    "external": 5
  },
  {
    "name": "@vantis/steering-app",
    "dir": "apps/web/steering-app",
    "glob": "apps/web/*",
    "kind": "surface",
    "lines": 7655,
    "deps": [
      "@fde/guard",
      "@fde/uikit",
      "@vantis/steering",
      "@veresk/surface"
    ],
    "external": 6
  },
  {
    "name": "@veresk/app",
    "dir": "apps/web/veresk-app",
    "glob": "apps/web/*",
    "kind": "surface",
    "lines": 9279,
    "deps": [
      "@fde/uikit",
      "@veresk/surface"
    ],
    "external": 6
  },
  {
    "name": "@veresk/surface",
    "dir": "packages/surface",
    "glob": "packages/*",
    "kind": "shared",
    "lines": 956,
    "deps": [
      "@fde/uikit"
    ],
    "external": 0
  }
];
