/**
 * Determinism, and why it is not optional.
 *
 * The whole estate is regenerated by one command. If that command produces
 * different rows each time, then every trap has to be re-found by hand after
 * every run, the acceptance case stops being derivable, and `db:check` becomes
 * a test of today's dice rather than of the design. So: a seeded PRNG, a frozen
 * epoch, and NO `Date.now()`, `Math.random()` or bare `new Date()` anywhere
 * below this file.
 *
 * ── ONE STREAM PER GENERATOR, FROM THE FIRST COMMIT ───────────────────────
 *
 * Pharma bought this lesson expensively and wrote it down in
 * `world-fingerprint.ts`: its entire estate came off ONE seeded stream, with
 * `buildOperations` destructuring the same helpers object `buildWorld` had been
 * drawing from. Any new generator that pulled a single number shifted every
 * value produced after it — different ids, different dates, different results —
 * and nothing detected it. Two 500-line files became untouchable for months as
 * a result, because no one could tell a refactor from a corruption.
 *
 * The fix is trivial and has to be there from the start: every generator gets
 * its OWN `makeHelpers(SEEDS.x)`. A separate stream cannot disturb another one,
 * so adding a sixth generator tomorrow changes nothing that exists today.
 *
 * `SEEDS` below is therefore an append-only list. Changing an existing value
 * regenerates that subsystem from scratch and invalidates anything measured
 * against it; adding a new one is free.
 */

/** mulberry32 — small, fast, good enough, and identical across Node versions. */
export type Rand = () => number;

export function rng(seed: number): Rand {
  let a = seed >>> 0;
  return function next() {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/**
 * One seed per generator. APPEND ONLY — see the header.
 *
 * The values are arbitrary and only have to be distinct. They are written as
 * plain decimals rather than something clever because the only property that
 * matters is that nobody reuses one by accident.
 */
export const SEEDS = {
  programs: 71_030_101,
  hardware: 71_030_202,
  requirements: 71_030_303,
  corpus: 71_030_404,
  effort: 71_030_505,
  // ── added when the estate was re-rooted in files, 2026-09-13 ──
  //
  // The four databases stopped being the customer's reality and became the
  // structured view WE produce. Requirements and effort are not in anybody's
  // database — they are in documents, and turning them into rows is the job.
  // Three more streams, each its own, so none of the above shifts.
  corpusRequirements: 71_030_606,
  corpusPmo: 71_030_707,
  corpusCode: 71_030_808,
} as const;

/**
 * TODAY, frozen.
 *
 * Every relative date in the estate is computed from this constant. The
 * acceptance case pins the K2 spec's Rev A → Rev B supersession at 2026-07-30
 * and the RFQ due date after it; those only stay in the right order if "now"
 * never moves.
 */
export const EPOCH = new Date(Date.UTC(2026, 8, 13)); // 2026-09-13

export interface Helpers {
  r: Rand;
  /** Inclusive on both ends. */
  int(lo: number, hi: number): number;
  pick<T>(arr: readonly T[]): T;
  chance(p: number): boolean;
  /** A number in [lo, hi] rounded to `dp` places. */
  num(lo: number, hi: number, dp?: number): number;
  shuffle<T>(arr: readonly T[]): T[];
  /** `n` distinct members of `arr`, or all of them if `n` is larger. */
  sample<T>(arr: readonly T[], n: number): T[];
  /** A date `days` from EPOCH, negative for the past, as `YYYY-MM-DD`. */
  day(days: number): string;
  /** A date between `loDays` and `hiDays` from EPOCH. */
  dayBetween(loDays: number, hiDays: number): string;
}

export function makeHelpers(seed: number): Helpers {
  const r = rng(seed);

  const int = (lo: number, hi: number) => lo + Math.floor(r() * (hi - lo + 1));
  const pick = <T,>(arr: readonly T[]): T => arr[Math.floor(r() * arr.length)];
  const chance = (p: number) => r() < p;
  const num = (lo: number, hi: number, dp = 2) => Number((lo + r() * (hi - lo)).toFixed(dp));
  /** Fisher-Yates on a copy, off the same stream, so it stays deterministic. */
  const shuffle = <T,>(arr: readonly T[]): T[] => {
    const a = [...arr];
    for (let i = a.length - 1; i > 0; i--) {
      const j = Math.floor(r() * (i + 1));
      [a[i], a[j]] = [a[j], a[i]];
    }
    return a;
  };
  const sample = <T,>(arr: readonly T[], n: number): T[] => shuffle(arr).slice(0, n);
  const day = (days: number): string => iso(addDays(EPOCH, days));
  const dayBetween = (loDays: number, hiDays: number): string => day(int(loDays, hiDays));

  return { r, int, pick, chance, num, shuffle, sample, day, dayBetween };
}

// ── date helpers, all pure and all relative to EPOCH ───────────────────────

export function addDays(d: Date, days: number): Date {
  return new Date(d.getTime() + days * 86_400_000);
}

/** `YYYY-MM-DD`. The seed WRITES strings; pg reads them back as `Date`. */
export function iso(d: Date): string {
  return d.toISOString().slice(0, 10);
}

/** A fixed calendar date, for the anchors that must not move at all. */
export function on(y: number, m: number, d: number): string {
  return iso(new Date(Date.UTC(y, m - 1, d)));
}

/** Whole years between two ISO days, for rate-card and comparables filtering. */
export function yearOf(isoDay: string): number {
  return Number(isoDay.slice(0, 4));
}
