/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as LearnAgenticRouteImport } from './routes/learn.agentic'
import { Route as LearnAnswerKeyRouteImport } from './routes/learn.answer-key'
import { Route as LearnArchitectureRouteImport } from './routes/learn.architecture'
import { Route as LearnAttentionRouteImport } from './routes/learn.attention'
import { Route as LearnCachingRouteImport } from './routes/learn.caching'
import { Route as LearnCeilingRouteImport } from './routes/learn.ceiling'
import { Route as LearnContextRouteImport } from './routes/learn.context'
import { Route as LearnCorrectiveRouteImport } from './routes/learn.corrective'
import { Route as LearnCostRouteImport } from './routes/learn.cost'
import { Route as LearnCredentialsRouteImport } from './routes/learn.credentials'
import { Route as LearnDriftRouteImport } from './routes/learn.drift'
import { Route as LearnEvalsRouteImport } from './routes/learn.evals'
import { Route as LearnFinetuningRouteImport } from './routes/learn.finetuning'
import { Route as LearnForensicsRouteImport } from './routes/learn.forensics'
import { Route as LearnGenerationRouteImport } from './routes/learn.generation'
import { Route as LearnGraphRouteImport } from './routes/learn.graph'
import { Route as LearnGuessingRouteImport } from './routes/learn.guessing'
import { Route as LearnHybridRouteImport } from './routes/learn.hybrid'
import { Route as LearnInjectionRouteImport } from './routes/learn.injection'
import { Route as LearnLoopRouteImport } from './routes/learn.loop'
import { Route as LearnMultimodalRouteImport } from './routes/learn.multimodal'
import { Route as LearnOrchestrationRouteImport } from './routes/learn.orchestration'
import { Route as LearnPipelinesRouteImport } from './routes/learn.pipelines'
import { Route as LearnRegressionsRouteImport } from './routes/learn.regressions'
import { Route as LearnResidencyRouteImport } from './routes/learn.residency'
import { Route as LearnRetrievalRouteImport } from './routes/learn.retrieval'
import { Route as LearnToolsRouteImport } from './routes/learn.tools'
import { Route as LearnVectorsRouteImport } from './routes/learn.vectors'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnRoute,
} as any)
const LearnAgenticRoute = LearnAgenticRouteImport.update({
  id: '/agentic',
  path: '/agentic',
  getParentRoute: () => LearnRoute,
} as any)
const LearnAnswerKeyRoute = LearnAnswerKeyRouteImport.update({
  id: '/answer-key',
  path: '/answer-key',
  getParentRoute: () => LearnRoute,
} as any)
const LearnArchitectureRoute = LearnArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => LearnRoute,
} as any)
const LearnAttentionRoute = LearnAttentionRouteImport.update({
  id: '/attention',
  path: '/attention',
  getParentRoute: () => LearnRoute,
} as any)
const LearnCachingRoute = LearnCachingRouteImport.update({
  id: '/caching',
  path: '/caching',
  getParentRoute: () => LearnRoute,
} as any)
const LearnCeilingRoute = LearnCeilingRouteImport.update({
  id: '/ceiling',
  path: '/ceiling',
  getParentRoute: () => LearnRoute,
} as any)
const LearnContextRoute = LearnContextRouteImport.update({
  id: '/context',
  path: '/context',
  getParentRoute: () => LearnRoute,
} as any)
const LearnCorrectiveRoute = LearnCorrectiveRouteImport.update({
  id: '/corrective',
  path: '/corrective',
  getParentRoute: () => LearnRoute,
} as any)
const LearnCostRoute = LearnCostRouteImport.update({
  id: '/cost',
  path: '/cost',
  getParentRoute: () => LearnRoute,
} as any)
const LearnCredentialsRoute = LearnCredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => LearnRoute,
} as any)
const LearnDriftRoute = LearnDriftRouteImport.update({
  id: '/drift',
  path: '/drift',
  getParentRoute: () => LearnRoute,
} as any)
const LearnEvalsRoute = LearnEvalsRouteImport.update({
  id: '/evals',
  path: '/evals',
  getParentRoute: () => LearnRoute,
} as any)
const LearnFinetuningRoute = LearnFinetuningRouteImport.update({
  id: '/finetuning',
  path: '/finetuning',
  getParentRoute: () => LearnRoute,
} as any)
const LearnForensicsRoute = LearnForensicsRouteImport.update({
  id: '/forensics',
  path: '/forensics',
  getParentRoute: () => LearnRoute,
} as any)
const LearnGenerationRoute = LearnGenerationRouteImport.update({
  id: '/generation',
  path: '/generation',
  getParentRoute: () => LearnRoute,
} as any)
const LearnGraphRoute = LearnGraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => LearnRoute,
} as any)
const LearnGuessingRoute = LearnGuessingRouteImport.update({
  id: '/guessing',
  path: '/guessing',
  getParentRoute: () => LearnRoute,
} as any)
const LearnHybridRoute = LearnHybridRouteImport.update({
  id: '/hybrid',
  path: '/hybrid',
  getParentRoute: () => LearnRoute,
} as any)
const LearnInjectionRoute = LearnInjectionRouteImport.update({
  id: '/injection',
  path: '/injection',
  getParentRoute: () => LearnRoute,
} as any)
const LearnLoopRoute = LearnLoopRouteImport.update({
  id: '/loop',
  path: '/loop',
  getParentRoute: () => LearnRoute,
} as any)
const LearnMultimodalRoute = LearnMultimodalRouteImport.update({
  id: '/multimodal',
  path: '/multimodal',
  getParentRoute: () => LearnRoute,
} as any)
const LearnOrchestrationRoute = LearnOrchestrationRouteImport.update({
  id: '/orchestration',
  path: '/orchestration',
  getParentRoute: () => LearnRoute,
} as any)
const LearnPipelinesRoute = LearnPipelinesRouteImport.update({
  id: '/pipelines',
  path: '/pipelines',
  getParentRoute: () => LearnRoute,
} as any)
const LearnRegressionsRoute = LearnRegressionsRouteImport.update({
  id: '/regressions',
  path: '/regressions',
  getParentRoute: () => LearnRoute,
} as any)
const LearnResidencyRoute = LearnResidencyRouteImport.update({
  id: '/residency',
  path: '/residency',
  getParentRoute: () => LearnRoute,
} as any)
const LearnRetrievalRoute = LearnRetrievalRouteImport.update({
  id: '/retrieval',
  path: '/retrieval',
  getParentRoute: () => LearnRoute,
} as any)
const LearnToolsRoute = LearnToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => LearnRoute,
} as any)
const LearnVectorsRoute = LearnVectorsRouteImport.update({
  id: '/vectors',
  path: '/vectors',
  getParentRoute: () => LearnRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/learn': typeof LearnRouteWithChildren
  '/learn/agentic': typeof LearnAgenticRoute
  '/learn/answer-key': typeof LearnAnswerKeyRoute
  '/learn/architecture': typeof LearnArchitectureRoute
  '/learn/attention': typeof LearnAttentionRoute
  '/learn/caching': typeof LearnCachingRoute
  '/learn/ceiling': typeof LearnCeilingRoute
  '/learn/context': typeof LearnContextRoute
  '/learn/corrective': typeof LearnCorrectiveRoute
  '/learn/cost': typeof LearnCostRoute
  '/learn/credentials': typeof LearnCredentialsRoute
  '/learn/drift': typeof LearnDriftRoute
  '/learn/evals': typeof LearnEvalsRoute
  '/learn/finetuning': typeof LearnFinetuningRoute
  '/learn/forensics': typeof LearnForensicsRoute
  '/learn/generation': typeof LearnGenerationRoute
  '/learn/graph': typeof LearnGraphRoute
  '/learn/guessing': typeof LearnGuessingRoute
  '/learn/hybrid': typeof LearnHybridRoute
  '/learn/injection': typeof LearnInjectionRoute
  '/learn/loop': typeof LearnLoopRoute
  '/learn/multimodal': typeof LearnMultimodalRoute
  '/learn/orchestration': typeof LearnOrchestrationRoute
  '/learn/pipelines': typeof LearnPipelinesRoute
  '/learn/regressions': typeof LearnRegressionsRoute
  '/learn/residency': typeof LearnResidencyRoute
  '/learn/retrieval': typeof LearnRetrievalRoute
  '/learn/tools': typeof LearnToolsRoute
  '/learn/vectors': typeof LearnVectorsRoute
  '/learn/': typeof LearnIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/learn/agentic': typeof LearnAgenticRoute
  '/learn/answer-key': typeof LearnAnswerKeyRoute
  '/learn/architecture': typeof LearnArchitectureRoute
  '/learn/attention': typeof LearnAttentionRoute
  '/learn/caching': typeof LearnCachingRoute
  '/learn/ceiling': typeof LearnCeilingRoute
  '/learn/context': typeof LearnContextRoute
  '/learn/corrective': typeof LearnCorrectiveRoute
  '/learn/cost': typeof LearnCostRoute
  '/learn/credentials': typeof LearnCredentialsRoute
  '/learn/drift': typeof LearnDriftRoute
  '/learn/evals': typeof LearnEvalsRoute
  '/learn/finetuning': typeof LearnFinetuningRoute
  '/learn/forensics': typeof LearnForensicsRoute
  '/learn/generation': typeof LearnGenerationRoute
  '/learn/graph': typeof LearnGraphRoute
  '/learn/guessing': typeof LearnGuessingRoute
  '/learn/hybrid': typeof LearnHybridRoute
  '/learn/injection': typeof LearnInjectionRoute
  '/learn/loop': typeof LearnLoopRoute
  '/learn/multimodal': typeof LearnMultimodalRoute
  '/learn/orchestration': typeof LearnOrchestrationRoute
  '/learn/pipelines': typeof LearnPipelinesRoute
  '/learn/regressions': typeof LearnRegressionsRoute
  '/learn/residency': typeof LearnResidencyRoute
  '/learn/retrieval': typeof LearnRetrievalRoute
  '/learn/tools': typeof LearnToolsRoute
  '/learn/vectors': typeof LearnVectorsRoute
  '/learn': typeof LearnIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/learn': typeof LearnRouteWithChildren
  '/learn/agentic': typeof LearnAgenticRoute
  '/learn/answer-key': typeof LearnAnswerKeyRoute
  '/learn/architecture': typeof LearnArchitectureRoute
  '/learn/attention': typeof LearnAttentionRoute
  '/learn/caching': typeof LearnCachingRoute
  '/learn/ceiling': typeof LearnCeilingRoute
  '/learn/context': typeof LearnContextRoute
  '/learn/corrective': typeof LearnCorrectiveRoute
  '/learn/cost': typeof LearnCostRoute
  '/learn/credentials': typeof LearnCredentialsRoute
  '/learn/drift': typeof LearnDriftRoute
  '/learn/evals': typeof LearnEvalsRoute
  '/learn/finetuning': typeof LearnFinetuningRoute
  '/learn/forensics': typeof LearnForensicsRoute
  '/learn/generation': typeof LearnGenerationRoute
  '/learn/graph': typeof LearnGraphRoute
  '/learn/guessing': typeof LearnGuessingRoute
  '/learn/hybrid': typeof LearnHybridRoute
  '/learn/injection': typeof LearnInjectionRoute
  '/learn/loop': typeof LearnLoopRoute
  '/learn/multimodal': typeof LearnMultimodalRoute
  '/learn/orchestration': typeof LearnOrchestrationRoute
  '/learn/pipelines': typeof LearnPipelinesRoute
  '/learn/regressions': typeof LearnRegressionsRoute
  '/learn/residency': typeof LearnResidencyRoute
  '/learn/retrieval': typeof LearnRetrievalRoute
  '/learn/tools': typeof LearnToolsRoute
  '/learn/vectors': typeof LearnVectorsRoute
  '/learn/': typeof LearnIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/learn'
    | '/learn/agentic'
    | '/learn/answer-key'
    | '/learn/architecture'
    | '/learn/attention'
    | '/learn/caching'
    | '/learn/ceiling'
    | '/learn/context'
    | '/learn/corrective'
    | '/learn/cost'
    | '/learn/credentials'
    | '/learn/drift'
    | '/learn/evals'
    | '/learn/finetuning'
    | '/learn/forensics'
    | '/learn/generation'
    | '/learn/graph'
    | '/learn/guessing'
    | '/learn/hybrid'
    | '/learn/injection'
    | '/learn/loop'
    | '/learn/multimodal'
    | '/learn/orchestration'
    | '/learn/pipelines'
    | '/learn/regressions'
    | '/learn/residency'
    | '/learn/retrieval'
    | '/learn/tools'
    | '/learn/vectors'
    | '/learn/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/learn/agentic'
    | '/learn/answer-key'
    | '/learn/architecture'
    | '/learn/attention'
    | '/learn/caching'
    | '/learn/ceiling'
    | '/learn/context'
    | '/learn/corrective'
    | '/learn/cost'
    | '/learn/credentials'
    | '/learn/drift'
    | '/learn/evals'
    | '/learn/finetuning'
    | '/learn/forensics'
    | '/learn/generation'
    | '/learn/graph'
    | '/learn/guessing'
    | '/learn/hybrid'
    | '/learn/injection'
    | '/learn/loop'
    | '/learn/multimodal'
    | '/learn/orchestration'
    | '/learn/pipelines'
    | '/learn/regressions'
    | '/learn/residency'
    | '/learn/retrieval'
    | '/learn/tools'
    | '/learn/vectors'
    | '/learn'
  id:
    | '__root__'
    | '/'
    | '/learn'
    | '/learn/agentic'
    | '/learn/answer-key'
    | '/learn/architecture'
    | '/learn/attention'
    | '/learn/caching'
    | '/learn/ceiling'
    | '/learn/context'
    | '/learn/corrective'
    | '/learn/cost'
    | '/learn/credentials'
    | '/learn/drift'
    | '/learn/evals'
    | '/learn/finetuning'
    | '/learn/forensics'
    | '/learn/generation'
    | '/learn/graph'
    | '/learn/guessing'
    | '/learn/hybrid'
    | '/learn/injection'
    | '/learn/loop'
    | '/learn/multimodal'
    | '/learn/orchestration'
    | '/learn/pipelines'
    | '/learn/regressions'
    | '/learn/residency'
    | '/learn/retrieval'
    | '/learn/tools'
    | '/learn/vectors'
    | '/learn/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LearnRoute: typeof LearnRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/agentic': {
      id: '/learn/agentic'
      path: '/agentic'
      fullPath: '/learn/agentic'
      preLoaderRoute: typeof LearnAgenticRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/answer-key': {
      id: '/learn/answer-key'
      path: '/answer-key'
      fullPath: '/learn/answer-key'
      preLoaderRoute: typeof LearnAnswerKeyRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/architecture': {
      id: '/learn/architecture'
      path: '/architecture'
      fullPath: '/learn/architecture'
      preLoaderRoute: typeof LearnArchitectureRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/attention': {
      id: '/learn/attention'
      path: '/attention'
      fullPath: '/learn/attention'
      preLoaderRoute: typeof LearnAttentionRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/caching': {
      id: '/learn/caching'
      path: '/caching'
      fullPath: '/learn/caching'
      preLoaderRoute: typeof LearnCachingRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/ceiling': {
      id: '/learn/ceiling'
      path: '/ceiling'
      fullPath: '/learn/ceiling'
      preLoaderRoute: typeof LearnCeilingRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/context': {
      id: '/learn/context'
      path: '/context'
      fullPath: '/learn/context'
      preLoaderRoute: typeof LearnContextRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/corrective': {
      id: '/learn/corrective'
      path: '/corrective'
      fullPath: '/learn/corrective'
      preLoaderRoute: typeof LearnCorrectiveRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/cost': {
      id: '/learn/cost'
      path: '/cost'
      fullPath: '/learn/cost'
      preLoaderRoute: typeof LearnCostRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/credentials': {
      id: '/learn/credentials'
      path: '/credentials'
      fullPath: '/learn/credentials'
      preLoaderRoute: typeof LearnCredentialsRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/drift': {
      id: '/learn/drift'
      path: '/drift'
      fullPath: '/learn/drift'
      preLoaderRoute: typeof LearnDriftRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/evals': {
      id: '/learn/evals'
      path: '/evals'
      fullPath: '/learn/evals'
      preLoaderRoute: typeof LearnEvalsRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/finetuning': {
      id: '/learn/finetuning'
      path: '/finetuning'
      fullPath: '/learn/finetuning'
      preLoaderRoute: typeof LearnFinetuningRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/forensics': {
      id: '/learn/forensics'
      path: '/forensics'
      fullPath: '/learn/forensics'
      preLoaderRoute: typeof LearnForensicsRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/generation': {
      id: '/learn/generation'
      path: '/generation'
      fullPath: '/learn/generation'
      preLoaderRoute: typeof LearnGenerationRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/graph': {
      id: '/learn/graph'
      path: '/graph'
      fullPath: '/learn/graph'
      preLoaderRoute: typeof LearnGraphRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/guessing': {
      id: '/learn/guessing'
      path: '/guessing'
      fullPath: '/learn/guessing'
      preLoaderRoute: typeof LearnGuessingRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/hybrid': {
      id: '/learn/hybrid'
      path: '/hybrid'
      fullPath: '/learn/hybrid'
      preLoaderRoute: typeof LearnHybridRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/injection': {
      id: '/learn/injection'
      path: '/injection'
      fullPath: '/learn/injection'
      preLoaderRoute: typeof LearnInjectionRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/loop': {
      id: '/learn/loop'
      path: '/loop'
      fullPath: '/learn/loop'
      preLoaderRoute: typeof LearnLoopRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/multimodal': {
      id: '/learn/multimodal'
      path: '/multimodal'
      fullPath: '/learn/multimodal'
      preLoaderRoute: typeof LearnMultimodalRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/orchestration': {
      id: '/learn/orchestration'
      path: '/orchestration'
      fullPath: '/learn/orchestration'
      preLoaderRoute: typeof LearnOrchestrationRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/pipelines': {
      id: '/learn/pipelines'
      path: '/pipelines'
      fullPath: '/learn/pipelines'
      preLoaderRoute: typeof LearnPipelinesRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/regressions': {
      id: '/learn/regressions'
      path: '/regressions'
      fullPath: '/learn/regressions'
      preLoaderRoute: typeof LearnRegressionsRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/residency': {
      id: '/learn/residency'
      path: '/residency'
      fullPath: '/learn/residency'
      preLoaderRoute: typeof LearnResidencyRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/retrieval': {
      id: '/learn/retrieval'
      path: '/retrieval'
      fullPath: '/learn/retrieval'
      preLoaderRoute: typeof LearnRetrievalRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/tools': {
      id: '/learn/tools'
      path: '/tools'
      fullPath: '/learn/tools'
      preLoaderRoute: typeof LearnToolsRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/vectors': {
      id: '/learn/vectors'
      path: '/vectors'
      fullPath: '/learn/vectors'
      preLoaderRoute: typeof LearnVectorsRouteImport
      parentRoute: typeof LearnRoute
    }
  }
}

interface LearnRouteChildren {
  LearnAgenticRoute: typeof LearnAgenticRoute
  LearnAnswerKeyRoute: typeof LearnAnswerKeyRoute
  LearnArchitectureRoute: typeof LearnArchitectureRoute
  LearnAttentionRoute: typeof LearnAttentionRoute
  LearnCachingRoute: typeof LearnCachingRoute
  LearnCeilingRoute: typeof LearnCeilingRoute
  LearnContextRoute: typeof LearnContextRoute
  LearnCorrectiveRoute: typeof LearnCorrectiveRoute
  LearnCostRoute: typeof LearnCostRoute
  LearnCredentialsRoute: typeof LearnCredentialsRoute
  LearnDriftRoute: typeof LearnDriftRoute
  LearnEvalsRoute: typeof LearnEvalsRoute
  LearnFinetuningRoute: typeof LearnFinetuningRoute
  LearnForensicsRoute: typeof LearnForensicsRoute
  LearnGenerationRoute: typeof LearnGenerationRoute
  LearnGraphRoute: typeof LearnGraphRoute
  LearnGuessingRoute: typeof LearnGuessingRoute
  LearnHybridRoute: typeof LearnHybridRoute
  LearnInjectionRoute: typeof LearnInjectionRoute
  LearnLoopRoute: typeof LearnLoopRoute
  LearnMultimodalRoute: typeof LearnMultimodalRoute
  LearnOrchestrationRoute: typeof LearnOrchestrationRoute
  LearnPipelinesRoute: typeof LearnPipelinesRoute
  LearnRegressionsRoute: typeof LearnRegressionsRoute
  LearnResidencyRoute: typeof LearnResidencyRoute
  LearnRetrievalRoute: typeof LearnRetrievalRoute
  LearnToolsRoute: typeof LearnToolsRoute
  LearnVectorsRoute: typeof LearnVectorsRoute
  LearnIndexRoute: typeof LearnIndexRoute
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnAgenticRoute: LearnAgenticRoute,
  LearnAnswerKeyRoute: LearnAnswerKeyRoute,
  LearnArchitectureRoute: LearnArchitectureRoute,
  LearnAttentionRoute: LearnAttentionRoute,
  LearnCachingRoute: LearnCachingRoute,
  LearnCeilingRoute: LearnCeilingRoute,
  LearnContextRoute: LearnContextRoute,
  LearnCorrectiveRoute: LearnCorrectiveRoute,
  LearnCostRoute: LearnCostRoute,
  LearnCredentialsRoute: LearnCredentialsRoute,
  LearnDriftRoute: LearnDriftRoute,
  LearnEvalsRoute: LearnEvalsRoute,
  LearnFinetuningRoute: LearnFinetuningRoute,
  LearnForensicsRoute: LearnForensicsRoute,
  LearnGenerationRoute: LearnGenerationRoute,
  LearnGraphRoute: LearnGraphRoute,
  LearnGuessingRoute: LearnGuessingRoute,
  LearnHybridRoute: LearnHybridRoute,
  LearnInjectionRoute: LearnInjectionRoute,
  LearnLoopRoute: LearnLoopRoute,
  LearnMultimodalRoute: LearnMultimodalRoute,
  LearnOrchestrationRoute: LearnOrchestrationRoute,
  LearnPipelinesRoute: LearnPipelinesRoute,
  LearnRegressionsRoute: LearnRegressionsRoute,
  LearnResidencyRoute: LearnResidencyRoute,
  LearnRetrievalRoute: LearnRetrievalRoute,
  LearnToolsRoute: LearnToolsRoute,
  LearnVectorsRoute: LearnVectorsRoute,
  LearnIndexRoute: LearnIndexRoute,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LearnRoute: LearnRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
