/**
 * GENERATED by `pnpm pharma:estate` — do not edit.
 *
 * Every table in the seven databases, its columns, and an exact row count as of
 * the date below. The prose about what each table HOLDS is not here: it is
 * hand-written in `estate-notes.ts`, typed against `EstateTableKey`, so a
 * table added without a note fails `pnpm typecheck`.
 */

export interface EstateColumn {
  name: string;
  /** One real value from the table, truncated. Never present for `mrd_kb`. */
  sample?: string;
  kind: 'text' | 'number' | 'date' | 'flag' | 'json' | 'other';
}

export interface EstateTable {
  name: string;
  columns: EstateColumn[];
  rows: number;
}

export interface EstateSystem {
  db: string;
  label: string;
  /** `mrd_kb` is the one that is not. It is a library, not a system of record. */
  isSystemOfRecord: boolean;
  tables: EstateTable[];
}

/** The day the counts were measured. Printed on the page beside them. */
export const MEASURED_AT = '2026-09-13';

/** The command that reproduces every number in this file. */
export const MEASURED_BY = 'pnpm pharma:estate';

export const TOTAL_ROWS = 5047;

export const ESTATE: EstateSystem[] = [
  {
    "db": "mrd_reg",
    "label": "standards & policies",
    "isSystemOfRecord": true,
    "tables": [
      {
        "name": "policies",
        "columns": [
          {
            "name": "policy_id",
            "kind": "text",
            "sample": "POL-EHS-02"
          },
          {
            "name": "title",
            "kind": "text",
            "sample": "Health, Safety and Enviro…"
          },
          {
            "name": "scope",
            "kind": "text",
            "sample": "global"
          },
          {
            "name": "owner_ref",
            "kind": "text",
            "sample": "EMP-0158"
          },
          {
            "name": "effective_from",
            "kind": "date",
            "sample": "2022-04-01"
          },
          {
            "name": "effective_to",
            "kind": "date"
          }
        ],
        "rows": 8
      },
      {
        "name": "sop_clause_links",
        "columns": [
          {
            "name": "link_id",
            "kind": "number",
            "sample": "1"
          },
          {
            "name": "revision_id",
            "kind": "text",
            "sample": "SOP-QC-014 Rev 5"
          },
          {
            "name": "clause_id",
            "kind": "text",
            "sample": "ANNEX16-1.5"
          },
          {
            "name": "relation",
            "kind": "text",
            "sample": "implements"
          }
        ],
        "rows": 34
      },
      {
        "name": "sop_revisions",
        "columns": [
          {
            "name": "revision_id",
            "kind": "text",
            "sample": "SOP-ENG-005 Rev 6"
          },
          {
            "name": "sop_id",
            "kind": "text",
            "sample": "SOP-ENG-005"
          },
          {
            "name": "revision_no",
            "kind": "number",
            "sample": "6"
          },
          {
            "name": "effective_from",
            "kind": "date",
            "sample": "2024-02-01"
          },
          {
            "name": "effective_to",
            "kind": "date"
          },
          {
            "name": "summary",
            "kind": "text",
            "sample": "Equipment qualification a…"
          },
          {
            "name": "change_summary",
            "kind": "text",
            "sample": "Requalification interval …"
          },
          {
            "name": "supersedes_revision_id",
            "kind": "text"
          },
          {
            "name": "change_control_ref",
            "kind": "text",
            "sample": "CC-24-0005"
          }
        ],
        "rows": 20
      },
      {
        "name": "sops",
        "columns": [
          {
            "name": "sop_id",
            "kind": "text",
            "sample": "SOP-ENG-005"
          },
          {
            "name": "title",
            "kind": "text",
            "sample": "Equipment Qualification a…"
          },
          {
            "name": "category",
            "kind": "text",
            "sample": "manufacturing"
          },
          {
            "name": "owning_department_ref",
            "kind": "text",
            "sample": "DEPT-ENG"
          }
        ],
        "rows": 12
      },
      {
        "name": "standard_clauses",
        "columns": [
          {
            "name": "clause_id",
            "kind": "text",
            "sample": "ANNEX16-1.5"
          },
          {
            "name": "standard_id",
            "kind": "text",
            "sample": "EU-GMP-ANNEX-16"
          },
          {
            "name": "clause_no",
            "kind": "text",
            "sample": "1.5"
          },
          {
            "name": "title",
            "kind": "text",
            "sample": "Responsibilities of the Q…"
          },
          {
            "name": "summary",
            "kind": "text",
            "sample": "The QP certifying a batch…"
          }
        ],
        "rows": 20
      },
      {
        "name": "standards",
        "columns": [
          {
            "name": "standard_id",
            "kind": "text",
            "sample": "CFR-210"
          },
          {
            "name": "body",
            "kind": "text",
            "sample": "FDA"
          },
          {
            "name": "code",
            "kind": "text",
            "sample": "21 CFR Part 210"
          },
          {
            "name": "title",
            "kind": "text",
            "sample": "cGMP in Manufacturing, Pr…"
          },
          {
            "name": "jurisdiction",
            "kind": "text",
            "sample": "US"
          },
          {
            "name": "in_force_from",
            "kind": "date",
            "sample": "1978-09-29"
          }
        ],
        "rows": 26
      }
    ]
  },
  {
    "db": "mrd_hcm",
    "label": "personnel & departments",
    "isSystemOfRecord": true,
    "tables": [
      {
        "name": "departments",
        "columns": [
          {
            "name": "department_id",
            "kind": "text",
            "sample": "DEPT-ENG"
          },
          {
            "name": "name",
            "kind": "text",
            "sample": "Engineering & Maintenance"
          },
          {
            "name": "function",
            "kind": "text",
            "sample": "manufacturing"
          },
          {
            "name": "site_ref",
            "kind": "text",
            "sample": "SITE-01"
          },
          {
            "name": "head_employee_ref",
            "kind": "text",
            "sample": "EMP-0147"
          }
        ],
        "rows": 8
      },
      {
        "name": "employees",
        "columns": [
          {
            "name": "employee_id",
            "kind": "text",
            "sample": "EMP-0101"
          },
          {
            "name": "full_name",
            "kind": "text",
            "sample": "Ingrid Bakker"
          },
          {
            "name": "position_id",
            "kind": "text",
            "sample": "POS-QAM"
          },
          {
            "name": "department_id",
            "kind": "text",
            "sample": "DEPT-QA"
          },
          {
            "name": "site_ref",
            "kind": "text",
            "sample": "SITE-01"
          },
          {
            "name": "hired_on",
            "kind": "date",
            "sample": "2017-11-19"
          },
          {
            "name": "left_on",
            "kind": "date"
          },
          {
            "name": "status",
            "kind": "text",
            "sample": "active"
          }
        ],
        "rows": 60
      },
      {
        "name": "positions",
        "columns": [
          {
            "name": "position_id",
            "kind": "text",
            "sample": "POS-BUY"
          },
          {
            "name": "title",
            "kind": "text",
            "sample": "Buyer"
          },
          {
            "name": "department_id",
            "kind": "text",
            "sample": "DEPT-SCM"
          },
          {
            "name": "gmp_critical",
            "kind": "flag",
            "sample": "no"
          }
        ],
        "rows": 15
      },
      {
        "name": "qualifications",
        "columns": [
          {
            "name": "qualification_id",
            "kind": "text",
            "sample": "QUAL-EMP-0101-AUD"
          },
          {
            "name": "employee_id",
            "kind": "text",
            "sample": "EMP-0101"
          },
          {
            "name": "kind",
            "kind": "text",
            "sample": "auditor"
          },
          {
            "name": "authority",
            "kind": "text",
            "sample": "Internal"
          },
          {
            "name": "register_no",
            "kind": "text"
          },
          {
            "name": "registered_on",
            "kind": "date",
            "sample": "2022-05-04"
          },
          {
            "name": "valid_until",
            "kind": "date",
            "sample": "2026-12-18"
          }
        ],
        "rows": 40
      },
      {
        "name": "signature_authority",
        "columns": [
          {
            "name": "authority_id",
            "kind": "number",
            "sample": "1"
          },
          {
            "name": "employee_id",
            "kind": "text",
            "sample": "EMP-0103"
          },
          {
            "name": "act",
            "kind": "text",
            "sample": "qp_certify"
          },
          {
            "name": "granted_on",
            "kind": "date",
            "sample": "2024-07-09"
          },
          {
            "name": "revoked_on",
            "kind": "date"
          }
        ],
        "rows": 28
      },
      {
        "name": "training_curricula",
        "columns": [
          {
            "name": "curriculum_id",
            "kind": "text",
            "sample": "TRN-AUD"
          },
          {
            "name": "code",
            "kind": "text",
            "sample": "AUD-01"
          },
          {
            "name": "title",
            "kind": "text",
            "sample": "Internal Auditor"
          },
          {
            "name": "validity_months",
            "kind": "number",
            "sample": "36"
          },
          {
            "name": "mandatory_for",
            "kind": "text",
            "sample": "quality"
          }
        ],
        "rows": 10
      },
      {
        "name": "training_records",
        "columns": [
          {
            "name": "record_id",
            "kind": "number",
            "sample": "1"
          },
          {
            "name": "employee_id",
            "kind": "text",
            "sample": "EMP-0101"
          },
          {
            "name": "curriculum_id",
            "kind": "text",
            "sample": "TRN-GMP-IND"
          },
          {
            "name": "completed_on",
            "kind": "date",
            "sample": "2026-02-08"
          },
          {
            "name": "expires_on",
            "kind": "date",
            "sample": "2029-02-08"
          },
          {
            "name": "score_pct",
            "kind": "number",
            "sample": "93"
          }
        ],
        "rows": 401
      }
    ]
  },
  {
    "db": "mrd_erp",
    "label": "products & materials",
    "isSystemOfRecord": true,
    "tables": [
      {
        "name": "bill_of_materials",
        "columns": [
          {
            "name": "bom_id",
            "kind": "number",
            "sample": "1"
          },
          {
            "name": "product_id",
            "kind": "text",
            "sample": "PRD-00141"
          },
          {
            "name": "ingredient_id",
            "kind": "text",
            "sample": "ING-API-IBU"
          },
          {
            "name": "version",
            "kind": "number",
            "sample": "2"
          },
          {
            "name": "effective_from",
            "kind": "date",
            "sample": "2023-01-01"
          },
          {
            "name": "effective_to",
            "kind": "date"
          },
          {
            "name": "qty_mg",
            "kind": "number",
            "sample": "470.565"
          },
          {
            "name": "tolerance_pct",
            "kind": "number",
            "sample": "3.90"
          }
        ],
        "rows": 56
      },
      {
        "name": "ingredients",
        "columns": [
          {
            "name": "ingredient_id",
            "kind": "text",
            "sample": "ING-API-AMB"
          },
          {
            "name": "name",
            "kind": "text",
            "sample": "Ambroxol hydrochloride"
          },
          {
            "name": "kind",
            "kind": "text",
            "sample": "API"
          },
          {
            "name": "cas_number",
            "kind": "text",
            "sample": "23828-92-4"
          },
          {
            "name": "compendial_ref",
            "kind": "text",
            "sample": "USP-AMB"
          }
        ],
        "rows": 18
      },
      {
        "name": "lot_material_consumption",
        "columns": [
          {
            "name": "consumption_id",
            "kind": "number",
            "sample": "1"
          },
          {
            "name": "lot_id",
            "kind": "text",
            "sample": "LOT-IBU200-2609-B"
          },
          {
            "name": "material_lot_id",
            "kind": "text",
            "sample": "MLOT-2407-0007"
          },
          {
            "name": "quantity_kg",
            "kind": "number",
            "sample": "6.904"
          }
        ],
        "rows": 190
      },
      {
        "name": "market_authorisations",
        "columns": [
          {
            "name": "ma_id",
            "kind": "text",
            "sample": "MA-AMB030-EU"
          },
          {
            "name": "product_id",
            "kind": "text",
            "sample": "PRD-00152"
          },
          {
            "name": "market",
            "kind": "text",
            "sample": "EU"
          },
          {
            "name": "ma_number",
            "kind": "text",
            "sample": "NL/H/5426/001"
          },
          {
            "name": "holder",
            "kind": "text",
            "sample": "Meridian Pharma B.V."
          },
          {
            "name": "status",
            "kind": "text",
            "sample": "valid"
          },
          {
            "name": "valid_from",
            "kind": "date",
            "sample": "2024-06-13"
          },
          {
            "name": "valid_to",
            "kind": "date"
          },
          {
            "name": "spec_version_ref",
            "kind": "text",
            "sample": "SPEC-AMB030-v3"
          }
        ],
        "rows": 24
      },
      {
        "name": "material_lots",
        "columns": [
          {
            "name": "material_lot_id",
            "kind": "text",
            "sample": "MLOT-2312-0091"
          },
          {
            "name": "ingredient_id",
            "kind": "text",
            "sample": "ING-API-ATO"
          },
          {
            "name": "supplier_id",
            "kind": "text",
            "sample": "SUP-08"
          },
          {
            "name": "received_on",
            "kind": "date",
            "sample": "2023-12-20"
          },
          {
            "name": "quantity_kg",
            "kind": "number",
            "sample": "541.544"
          },
          {
            "name": "coa_ref",
            "kind": "text",
            "sample": "COA-SUP-08-99018"
          },
          {
            "name": "status",
            "kind": "text",
            "sample": "released"
          }
        ],
        "rows": 122
      },
      {
        "name": "product_lots",
        "columns": [
          {
            "name": "lot_id",
            "kind": "text",
            "sample": "LOT-AMB030-2402-A"
          },
          {
            "name": "product_id",
            "kind": "text",
            "sample": "PRD-00152"
          },
          {
            "name": "campaign",
            "kind": "text",
            "sample": "2402"
          },
          {
            "name": "sub_batch",
            "kind": "text",
            "sample": "A"
          },
          {
            "name": "market",
            "kind": "text",
            "sample": "EU"
          },
          {
            "name": "quantity_units",
            "kind": "number",
            "sample": "211007"
          },
          {
            "name": "manufactured_on",
            "kind": "date",
            "sample": "2024-02-21"
          },
          {
            "name": "expiry_on",
            "kind": "date",
            "sample": "2027-02-21"
          },
          {
            "name": "work_order_ref",
            "kind": "text",
            "sample": "WO-24-0133"
          },
          {
            "name": "spec_version_ref",
            "kind": "text",
            "sample": "SPEC-AMB030-v3"
          },
          {
            "name": "status",
            "kind": "text",
            "sample": "released"
          }
        ],
        "rows": 94
      },
      {
        "name": "products",
        "columns": [
          {
            "name": "product_id",
            "kind": "text",
            "sample": "PRD-00141"
          },
          {
            "name": "product_code",
            "kind": "text",
            "sample": "IBU200"
          },
          {
            "name": "name",
            "kind": "text",
            "sample": "Ibuprofen 200 mg film-coa…"
          },
          {
            "name": "dosage_form",
            "kind": "text",
            "sample": "tablet"
          },
          {
            "name": "strength",
            "kind": "text",
            "sample": "200 mg"
          },
          {
            "name": "atc_code",
            "kind": "text",
            "sample": "M01AE01"
          },
          {
            "name": "status",
            "kind": "text",
            "sample": "commercial"
          }
        ],
        "rows": 12
      },
      {
        "name": "suppliers",
        "columns": [
          {
            "name": "supplier_id",
            "kind": "text",
            "sample": "SUP-01"
          },
          {
            "name": "name",
            "kind": "text",
            "sample": "Rhine Fine Chemicals GmbH"
          },
          {
            "name": "country",
            "kind": "text",
            "sample": "DE"
          },
          {
            "name": "qualified_from",
            "kind": "date",
            "sample": "2017-05-05"
          },
          {
            "name": "disqualified_on",
            "kind": "date"
          },
          {
            "name": "disqualified_reason",
            "kind": "text"
          }
        ],
        "rows": 8
      }
    ]
  },
  {
    "db": "mrd_mes",
    "label": "facilities & manufacturing",
    "isSystemOfRecord": true,
    "tables": [
      {
        "name": "deviations",
        "columns": [
          {
            "name": "deviation_id",
            "kind": "text",
            "sample": "DEV-24-0002"
          },
          {
            "name": "work_order_id",
            "kind": "text",
            "sample": "WO-24-0120"
          },
          {
            "name": "step_id",
            "kind": "text"
          },
          {
            "name": "raised_on",
            "kind": "date",
            "sample": "2024-10-15"
          },
          {
            "name": "raised_by_ref",
            "kind": "text",
            "sample": "EMP-0127"
          },
          {
            "name": "severity",
            "kind": "text",
            "sample": "minor"
          },
          {
            "name": "description",
            "kind": "text",
            "sample": "Printed batch record page…"
          },
          {
            "name": "status",
            "kind": "text",
            "sample": "closed"
          },
          {
            "name": "capa_ref",
            "kind": "text"
          }
        ],
        "rows": 22
      },
      {
        "name": "equipment",
        "columns": [
          {
            "name": "equipment_id",
            "kind": "text",
            "sample": "EQ-0111"
          },
          {
            "name": "line_id",
            "kind": "text",
            "sample": "LINE-01-T1"
          },
          {
            "name": "name",
            "kind": "text",
            "sample": "Fluid bed granulator"
          },
          {
            "name": "kind",
            "kind": "text",
            "sample": "granulator"
          },
          {
            "name": "serial_no",
            "kind": "text",
            "sample": "SN-531799"
          }
        ],
        "rows": 24
      },
      {
        "name": "equipment_qualification",
        "columns": [
          {
            "name": "qualification_id",
            "kind": "number",
            "sample": "1"
          },
          {
            "name": "equipment_id",
            "kind": "text",
            "sample": "EQ-0111"
          },
          {
            "name": "kind",
            "kind": "text",
            "sample": "IQ"
          },
          {
            "name": "performed_on",
            "kind": "date",
            "sample": "2022-05-10"
          },
          {
            "name": "valid_until",
            "kind": "date",
            "sample": "2032-05-09"
          },
          {
            "name": "status",
            "kind": "text",
            "sample": "passed"
          },
          {
            "name": "performed_by_ref",
            "kind": "text",
            "sample": "EMP-0147"
          }
        ],
        "rows": 50
      },
      {
        "name": "lines",
        "columns": [
          {
            "name": "line_id",
            "kind": "text",
            "sample": "LINE-01-C1"
          },
          {
            "name": "site_id",
            "kind": "text",
            "sample": "SITE-01"
          },
          {
            "name": "name",
            "kind": "text",
            "sample": "Capsule line 1"
          },
          {
            "name": "building",
            "kind": "text",
            "sample": "B1"
          },
          {
            "name": "room",
            "kind": "text",
            "sample": "R-112"
          },
          {
            "name": "cleanroom_grade",
            "kind": "text",
            "sample": "D"
          },
          {
            "name": "capability",
            "kind": "text",
            "sample": "capsule"
          }
        ],
        "rows": 6
      },
      {
        "name": "process_parameters",
        "columns": [
          {
            "name": "parameter_id",
            "kind": "number",
            "sample": "1"
          },
          {
            "name": "step_id",
            "kind": "text",
            "sample": "WO-26-0417-S02"
          },
          {
            "name": "name",
            "kind": "text",
            "sample": "Compression force"
          },
          {
            "name": "value_num",
            "kind": "number",
            "sample": "13.9691"
          },
          {
            "name": "unit",
            "kind": "text",
            "sample": "kN"
          },
          {
            "name": "lower_limit",
            "kind": "number",
            "sample": "8.0000"
          },
          {
            "name": "upper_limit",
            "kind": "number",
            "sample": "16.0000"
          },
          {
            "name": "in_spec",
            "kind": "flag",
            "sample": "yes"
          }
        ],
        "rows": 564
      },
      {
        "name": "process_steps",
        "columns": [
          {
            "name": "step_id",
            "kind": "text",
            "sample": "WO-24-0100-S01"
          },
          {
            "name": "work_order_id",
            "kind": "text",
            "sample": "WO-24-0100"
          },
          {
            "name": "seq",
            "kind": "number",
            "sample": "1"
          },
          {
            "name": "name",
            "kind": "text",
            "sample": "Dispensing"
          },
          {
            "name": "started_at",
            "kind": "date",
            "sample": "2024-02-13"
          },
          {
            "name": "ended_at",
            "kind": "date",
            "sample": "2024-02-13"
          },
          {
            "name": "equipment_ref",
            "kind": "text",
            "sample": "EQ-0115"
          },
          {
            "name": "performed_by_ref",
            "kind": "text",
            "sample": "EMP-0130"
          },
          {
            "name": "verified_by_ref",
            "kind": "text",
            "sample": "EMP-0127"
          }
        ],
        "rows": 564
      },
      {
        "name": "sites",
        "columns": [
          {
            "name": "site_id",
            "kind": "text",
            "sample": "SITE-01"
          },
          {
            "name": "name",
            "kind": "text",
            "sample": "Meridian Pharma Leiden"
          },
          {
            "name": "city",
            "kind": "text",
            "sample": "Leiden"
          },
          {
            "name": "country",
            "kind": "text",
            "sample": "NL"
          },
          {
            "name": "gmp_certificate_no",
            "kind": "text",
            "sample": "NL/GMP/2024/0418"
          },
          {
            "name": "gmp_valid_from",
            "kind": "date",
            "sample": "2024-03-01"
          },
          {
            "name": "gmp_valid_to",
            "kind": "date",
            "sample": "2027-02-28"
          }
        ],
        "rows": 2
      },
      {
        "name": "work_orders",
        "columns": [
          {
            "name": "work_order_id",
            "kind": "text",
            "sample": "WO-24-0100"
          },
          {
            "name": "line_id",
            "kind": "text",
            "sample": "LINE-01-T2"
          },
          {
            "name": "product_ref",
            "kind": "text",
            "sample": "PRD-00141"
          },
          {
            "name": "lot_ref",
            "kind": "text",
            "sample": "LOT-IBU200-2402-A"
          },
          {
            "name": "planned_start",
            "kind": "date",
            "sample": "2024-02-11"
          },
          {
            "name": "actual_start",
            "kind": "date",
            "sample": "2024-02-13"
          },
          {
            "name": "actual_end",
            "kind": "date",
            "sample": "2024-02-16"
          },
          {
            "name": "status",
            "kind": "text",
            "sample": "completed"
          },
          {
            "name": "governing_sop_ref",
            "kind": "text",
            "sample": "SOP-MFG-022 Rev 3"
          },
          {
            "name": "signed_by_ref",
            "kind": "text",
            "sample": "EMP-0127"
          },
          {
            "name": "signed_on",
            "kind": "date",
            "sample": "2024-02-17"
          }
        ],
        "rows": 94
      }
    ]
  },
  {
    "db": "mrd_qms",
    "label": "quality",
    "isSystemOfRecord": true,
    "tables": [
      {
        "name": "audits",
        "columns": [
          {
            "name": "audit_id",
            "kind": "text",
            "sample": "AUD-25-0002"
          },
          {
            "name": "kind",
            "kind": "text",
            "sample": "supplier"
          },
          {
            "name": "subject_ref",
            "kind": "text",
            "sample": "SUP-03"
          },
          {
            "name": "performed_on",
            "kind": "date",
            "sample": "2025-03-25"
          },
          {
            "name": "lead_auditor_ref",
            "kind": "text",
            "sample": "EMP-0107"
          },
          {
            "name": "findings_count",
            "kind": "number",
            "sample": "3"
          },
          {
            "name": "outcome",
            "kind": "text",
            "sample": "minor"
          }
        ],
        "rows": 4
      },
      {
        "name": "batch_dispositions",
        "columns": [
          {
            "name": "disposition_id",
            "kind": "text",
            "sample": "DISP-24-0007"
          },
          {
            "name": "lot_ref",
            "kind": "text",
            "sample": "LOT-CET010-2408-A"
          },
          {
            "name": "market",
            "kind": "text",
            "sample": "EU"
          },
          {
            "name": "decision",
            "kind": "text",
            "sample": "released"
          },
          {
            "name": "decided_on",
            "kind": "date",
            "sample": "2024-08-21"
          },
          {
            "name": "decided_by_ref",
            "kind": "text",
            "sample": "EMP-0103"
          },
          {
            "name": "governing_sop_ref",
            "kind": "text",
            "sample": "SOP-QC-014 Rev 6"
          },
          {
            "name": "qp_certified",
            "kind": "flag",
            "sample": "yes"
          }
        ],
        "rows": 94
      },
      {
        "name": "capas",
        "columns": [
          {
            "name": "capa_id",
            "kind": "text",
            "sample": "CAPA-24-0101"
          },
          {
            "name": "opened_on",
            "kind": "date",
            "sample": "2024-11-24"
          },
          {
            "name": "due_on",
            "kind": "date",
            "sample": "2025-02-22"
          },
          {
            "name": "closed_on",
            "kind": "date",
            "sample": "2025-02-13"
          },
          {
            "name": "source",
            "kind": "text",
            "sample": "deviation"
          },
          {
            "name": "source_ref",
            "kind": "text",
            "sample": "DEV-25-0001"
          },
          {
            "name": "owner_ref",
            "kind": "text",
            "sample": "EMP-0111"
          },
          {
            "name": "description",
            "kind": "text",
            "sample": "Corrective action followi…"
          },
          {
            "name": "status",
            "kind": "text",
            "sample": "closed"
          }
        ],
        "rows": 13
      },
      {
        "name": "change_controls",
        "columns": [
          {
            "name": "change_id",
            "kind": "text",
            "sample": "CC-24-0005"
          },
          {
            "name": "opened_on",
            "kind": "date",
            "sample": "2023-11-06"
          },
          {
            "name": "implemented_on",
            "kind": "date",
            "sample": "2024-02-01"
          },
          {
            "name": "description",
            "kind": "text",
            "sample": "Set tablet press requalif…"
          },
          {
            "name": "affected_sop_ref",
            "kind": "text",
            "sample": "SOP-ENG-005"
          },
          {
            "name": "approved_by_ref",
            "kind": "text",
            "sample": "EMP-0101"
          },
          {
            "name": "status",
            "kind": "text",
            "sample": "implemented"
          }
        ],
        "rows": 5
      },
      {
        "name": "complaints",
        "columns": [
          {
            "name": "complaint_id",
            "kind": "text",
            "sample": "CMP-0001"
          },
          {
            "name": "received_on",
            "kind": "date",
            "sample": "2025-11-27"
          },
          {
            "name": "channel",
            "kind": "text",
            "sample": "phone"
          },
          {
            "name": "reporter_kind",
            "kind": "text",
            "sample": "pharmacist"
          },
          {
            "name": "reporter_ref",
            "kind": "text",
            "sample": "CNS-0016"
          },
          {
            "name": "market",
            "kind": "text",
            "sample": "EU"
          },
          {
            "name": "product_ref",
            "kind": "text",
            "sample": "PRD-00143"
          },
          {
            "name": "lot_ref",
            "kind": "text",
            "sample": "LOT-AMX250-2410-A"
          },
          {
            "name": "lot_stated",
            "kind": "text",
            "sample": "LOT-AMX250-2410-A"
          },
          {
            "name": "category",
            "kind": "text",
            "sample": "packaging"
          },
          {
            "name": "is_adverse_event",
            "kind": "flag",
            "sample": "no"
          },
          {
            "name": "severity",
            "kind": "text",
            "sample": "major"
          },
          {
            "name": "narrative",
            "kind": "text",
            "sample": "Child-resistant closure d…"
          },
          {
            "name": "status",
            "kind": "text",
            "sample": "closed"
          },
          {
            "name": "opened_by_ref",
            "kind": "text",
            "sample": "EMP-0106"
          },
          {
            "name": "closed_on",
            "kind": "date",
            "sample": "2026-01-05"
          },
          {
            "name": "linked_deviation_ref",
            "kind": "text"
          },
          {
            "name": "linked_capa_ref",
            "kind": "text"
          }
        ],
        "rows": 41
      },
      {
        "name": "lab_events",
        "columns": [
          {
            "name": "event_id",
            "kind": "text",
            "sample": "LEV-000001"
          },
          {
            "name": "test_ref",
            "kind": "text",
            "sample": "QC-26-000001"
          },
          {
            "name": "event_seq",
            "kind": "number",
            "sample": "1"
          },
          {
            "name": "occurred_at",
            "kind": "date",
            "sample": "2026-09-02"
          },
          {
            "name": "performed_by_ref",
            "kind": "text",
            "sample": "EMP-0118"
          },
          {
            "name": "action",
            "kind": "text",
            "sample": "system_suitability"
          },
          {
            "name": "result_num",
            "kind": "number"
          },
          {
            "name": "unit",
            "kind": "text"
          },
          {
            "name": "reason",
            "kind": "text",
            "sample": "Five replicate injections…"
          },
          {
            "name": "supersedes_event_ref",
            "kind": "text"
          },
          {
            "name": "instrument_ref",
            "kind": "text",
            "sample": "EQ-0123"
          }
        ],
        "rows": 205
      },
      {
        "name": "oos_investigations",
        "columns": [
          {
            "name": "oos_id",
            "kind": "text",
            "sample": "OOS-26-0001"
          },
          {
            "name": "test_id",
            "kind": "text",
            "sample": "QC-26-000006"
          },
          {
            "name": "opened_on",
            "kind": "date",
            "sample": "2026-09-05"
          },
          {
            "name": "closed_on",
            "kind": "date",
            "sample": "2026-09-14"
          },
          {
            "name": "phase",
            "kind": "text",
            "sample": "IA"
          },
          {
            "name": "root_cause",
            "kind": "text",
            "sample": "Sample preparation error …"
          },
          {
            "name": "outcome",
            "kind": "text",
            "sample": "lab_error"
          },
          {
            "name": "approved_by_ref",
            "kind": "text",
            "sample": "EMP-0113"
          }
        ],
        "rows": 2
      },
      {
        "name": "qc_tests",
        "columns": [
          {
            "name": "test_id",
            "kind": "text",
            "sample": "QC-24-000031"
          },
          {
            "name": "lot_ref",
            "kind": "text",
            "sample": "LOT-CET010-2408-A"
          },
          {
            "name": "method_id",
            "kind": "text",
            "sample": "MTH-ASSAY"
          },
          {
            "name": "attribute",
            "kind": "text",
            "sample": "assay"
          },
          {
            "name": "stage",
            "kind": "text",
            "sample": "release"
          },
          {
            "name": "sampled_on",
            "kind": "date",
            "sample": "2024-08-16"
          },
          {
            "name": "tested_on",
            "kind": "date",
            "sample": "2024-08-17"
          },
          {
            "name": "analyst_ref",
            "kind": "text",
            "sample": "EMP-0122"
          },
          {
            "name": "spec_version_ref",
            "kind": "text",
            "sample": "SPEC-CET010-v3"
          },
          {
            "name": "result_num",
            "kind": "number",
            "sample": "98.2511"
          },
          {
            "name": "unit",
            "kind": "text",
            "sample": "%"
          },
          {
            "name": "in_spec",
            "kind": "flag",
            "sample": "yes"
          },
          {
            "name": "retest_of_test_id",
            "kind": "text"
          }
        ],
        "rows": 473
      },
      {
        "name": "spec_limits",
        "columns": [
          {
            "name": "limit_id",
            "kind": "number",
            "sample": "1"
          },
          {
            "name": "spec_version_id",
            "kind": "text",
            "sample": "SPEC-IBU200-v1"
          },
          {
            "name": "method_id",
            "kind": "text",
            "sample": "MTH-ASSAY"
          },
          {
            "name": "attribute",
            "kind": "text",
            "sample": "assay"
          },
          {
            "name": "lower_limit",
            "kind": "number",
            "sample": "95.0000"
          },
          {
            "name": "upper_limit",
            "kind": "number",
            "sample": "105.0000"
          },
          {
            "name": "unit",
            "kind": "text",
            "sample": "%"
          }
        ],
        "rows": 305
      },
      {
        "name": "specification_versions",
        "columns": [
          {
            "name": "spec_version_id",
            "kind": "text",
            "sample": "SPEC-AMB030-US-v1"
          },
          {
            "name": "spec_id",
            "kind": "text",
            "sample": "SPEC-AMB030-US"
          },
          {
            "name": "version",
            "kind": "number",
            "sample": "1"
          },
          {
            "name": "effective_from",
            "kind": "date",
            "sample": "2019-01-01"
          },
          {
            "name": "effective_to",
            "kind": "date",
            "sample": "2020-07-31"
          },
          {
            "name": "standard_ref",
            "kind": "text",
            "sample": "USP-AMB"
          }
        ],
        "rows": 61
      },
      {
        "name": "specifications",
        "columns": [
          {
            "name": "spec_id",
            "kind": "text",
            "sample": "SPEC-AMB030"
          },
          {
            "name": "product_ref",
            "kind": "text",
            "sample": "PRD-00152"
          },
          {
            "name": "market",
            "kind": "text",
            "sample": "EU"
          },
          {
            "name": "title",
            "kind": "text",
            "sample": "Ambroxol 30 mg/5 ml oral …"
          }
        ],
        "rows": 24
      },
      {
        "name": "test_methods",
        "columns": [
          {
            "name": "method_id",
            "kind": "text",
            "sample": "MTH-ASSAY"
          },
          {
            "name": "code",
            "kind": "text",
            "sample": "AS-HPLC"
          },
          {
            "name": "title",
            "kind": "text",
            "sample": "Assay by HPLC"
          },
          {
            "name": "technique",
            "kind": "text",
            "sample": "HPLC"
          },
          {
            "name": "compendial_ref",
            "kind": "text",
            "sample": "CFR-211.160"
          }
        ],
        "rows": 10
      }
    ]
  },
  {
    "db": "mrd_tms",
    "label": "distribution & fleet",
    "isSystemOfRecord": true,
    "tables": [
      {
        "name": "consignees",
        "columns": [
          {
            "name": "consignee_id",
            "kind": "text",
            "sample": "CNS-0011"
          },
          {
            "name": "name",
            "kind": "text",
            "sample": "Brocacef Groothandel"
          },
          {
            "name": "country",
            "kind": "text",
            "sample": "NL"
          },
          {
            "name": "market",
            "kind": "text",
            "sample": "EU"
          },
          {
            "name": "licence_no",
            "kind": "text",
            "sample": "WDA-71309"
          },
          {
            "name": "kind",
            "kind": "text",
            "sample": "wholesaler"
          }
        ],
        "rows": 10
      },
      {
        "name": "drivers",
        "columns": [
          {
            "name": "driver_id",
            "kind": "text",
            "sample": "DRV-001"
          },
          {
            "name": "full_name",
            "kind": "text",
            "sample": "Ruud Novak"
          },
          {
            "name": "licence_no",
            "kind": "text",
            "sample": "C+E-6618967"
          },
          {
            "name": "employee_ref",
            "kind": "text",
            "sample": "EMP-0149"
          }
        ],
        "rows": 10
      },
      {
        "name": "routes",
        "columns": [
          {
            "name": "route_id",
            "kind": "number",
            "sample": "1"
          },
          {
            "name": "shipment_id",
            "kind": "text",
            "sample": "SHP-26-1180"
          },
          {
            "name": "seq",
            "kind": "number",
            "sample": "1"
          },
          {
            "name": "from_location",
            "kind": "text",
            "sample": "Leiden, NL"
          },
          {
            "name": "to_location",
            "kind": "text",
            "sample": "Venlo, NL"
          },
          {
            "name": "departed_at",
            "kind": "date",
            "sample": "2026-08-24"
          },
          {
            "name": "arrived_at",
            "kind": "date",
            "sample": "2026-08-24"
          },
          {
            "name": "distance_km",
            "kind": "number",
            "sample": "182.4"
          }
        ],
        "rows": 74
      },
      {
        "name": "shipment_lines",
        "columns": [
          {
            "name": "line_id",
            "kind": "number",
            "sample": "1"
          },
          {
            "name": "shipment_id",
            "kind": "text",
            "sample": "SHP-26-1180"
          },
          {
            "name": "lot_ref",
            "kind": "text",
            "sample": "LOT-LAT005-2608-A"
          },
          {
            "name": "quantity_units",
            "kind": "number",
            "sample": "14200"
          },
          {
            "name": "sscc",
            "kind": "text",
            "sample": "00345678954329075"
          }
        ],
        "rows": 39
      },
      {
        "name": "shipments",
        "columns": [
          {
            "name": "shipment_id",
            "kind": "text",
            "sample": "SHP-24-1002"
          },
          {
            "name": "warehouse_id",
            "kind": "text",
            "sample": "WH-EU-02"
          },
          {
            "name": "consignee_id",
            "kind": "text",
            "sample": "CNS-0012"
          },
          {
            "name": "truck_id",
            "kind": "text",
            "sample": "TRK-03"
          },
          {
            "name": "driver_id",
            "kind": "text",
            "sample": "DRV-001"
          },
          {
            "name": "dispatched_on",
            "kind": "date",
            "sample": "2024-10-16"
          },
          {
            "name": "delivered_on",
            "kind": "date",
            "sample": "2024-10-17"
          },
          {
            "name": "status",
            "kind": "text",
            "sample": "delivered"
          },
          {
            "name": "required_temp_min",
            "kind": "number",
            "sample": "15.00"
          },
          {
            "name": "required_temp_max",
            "kind": "number",
            "sample": "25.00"
          }
        ],
        "rows": 39
      },
      {
        "name": "telematics_readings",
        "columns": [
          {
            "name": "reading_id",
            "kind": "number",
            "sample": "1"
          },
          {
            "name": "truck_id",
            "kind": "text",
            "sample": "TRK-07"
          },
          {
            "name": "shipment_id",
            "kind": "text",
            "sample": "SHP-26-1180"
          },
          {
            "name": "recorded_at",
            "kind": "date",
            "sample": "2026-08-24"
          },
          {
            "name": "temp_c",
            "kind": "number",
            "sample": "5.24"
          },
          {
            "name": "gps_lat",
            "kind": "number",
            "sample": "51.244215"
          },
          {
            "name": "gps_lon",
            "kind": "number",
            "sample": "6.286098"
          }
        ],
        "rows": 959
      },
      {
        "name": "trucks",
        "columns": [
          {
            "name": "truck_id",
            "kind": "text",
            "sample": "TRK-01"
          },
          {
            "name": "plate",
            "kind": "text",
            "sample": "DE-437-PZ"
          },
          {
            "name": "make",
            "kind": "text",
            "sample": "Scania"
          },
          {
            "name": "model",
            "kind": "text",
            "sample": "XF 480"
          },
          {
            "name": "refrigerated",
            "kind": "flag",
            "sample": "no"
          },
          {
            "name": "telematics_unit_id",
            "kind": "text",
            "sample": "TU-89405"
          },
          {
            "name": "in_service_from",
            "kind": "date",
            "sample": "2023-09-14"
          },
          {
            "name": "in_service_to",
            "kind": "date"
          }
        ],
        "rows": 8
      },
      {
        "name": "warehouses",
        "columns": [
          {
            "name": "warehouse_id",
            "kind": "text",
            "sample": "WH-EU-01"
          },
          {
            "name": "name",
            "kind": "text",
            "sample": "Leiden finished goods"
          },
          {
            "name": "site_ref",
            "kind": "text",
            "sample": "SITE-01"
          },
          {
            "name": "country",
            "kind": "text",
            "sample": "NL"
          },
          {
            "name": "gdp_licence_no",
            "kind": "text",
            "sample": "NL/GDP/2024/1142"
          },
          {
            "name": "licence_valid_to",
            "kind": "date",
            "sample": "2028-01-31"
          }
        ],
        "rows": 3
      }
    ]
  },
  {
    "db": "mrd_kb",
    "label": "knowledge base",
    "isSystemOfRecord": false,
    "tables": [
      {
        "name": "ask_history",
        "columns": [
          {
            "name": "id",
            "kind": "number"
          },
          {
            "name": "ts",
            "kind": "date"
          },
          {
            "name": "question",
            "kind": "text"
          },
          {
            "name": "loop",
            "kind": "text"
          },
          {
            "name": "surface",
            "kind": "text"
          },
          {
            "name": "answer",
            "kind": "json"
          },
          {
            "name": "failure",
            "kind": "json"
          },
          {
            "name": "run",
            "kind": "json"
          },
          {
            "name": "trace",
            "kind": "json"
          },
          {
            "name": "kind",
            "kind": "text"
          }
        ],
        "rows": 42
      },
      {
        "name": "document_chunks",
        "columns": [
          {
            "name": "id",
            "kind": "text"
          },
          {
            "name": "content",
            "kind": "text"
          },
          {
            "name": "metadata",
            "kind": "json"
          },
          {
            "name": "vector",
            "kind": "other"
          },
          {
            "name": "content_ts",
            "kind": "other"
          }
        ],
        "rows": 75
      },
      {
        "name": "document_relations",
        "columns": [
          {
            "name": "from_id",
            "kind": "text"
          },
          {
            "name": "verb",
            "kind": "text"
          },
          {
            "name": "to_ref",
            "kind": "text"
          }
        ],
        "rows": 14
      },
      {
        "name": "documents",
        "columns": [
          {
            "name": "document_id",
            "kind": "text"
          },
          {
            "name": "doc_type",
            "kind": "text"
          },
          {
            "name": "title",
            "kind": "text"
          },
          {
            "name": "body",
            "kind": "text"
          },
          {
            "name": "edition",
            "kind": "text"
          },
          {
            "name": "effective_on",
            "kind": "date"
          },
          {
            "name": "expires_on",
            "kind": "date"
          },
          {
            "name": "status",
            "kind": "text"
          },
          {
            "name": "facets",
            "kind": "json"
          },
          {
            "name": "content_sha",
            "kind": "text"
          },
          {
            "name": "source_name",
            "kind": "text"
          },
          {
            "name": "source_path",
            "kind": "text"
          },
          {
            "name": "updated_at",
            "kind": "date"
          }
        ],
        "rows": 5
      }
    ]
  }
];

/** Every `<db>.<table>` in the estate. `estate-notes.ts` must cover all of them. */
export type EstateTableKey =
  | 'mrd_reg.policies'
  | 'mrd_reg.sop_clause_links'
  | 'mrd_reg.sop_revisions'
  | 'mrd_reg.sops'
  | 'mrd_reg.standard_clauses'
  | 'mrd_reg.standards'
  | 'mrd_hcm.departments'
  | 'mrd_hcm.employees'
  | 'mrd_hcm.positions'
  | 'mrd_hcm.qualifications'
  | 'mrd_hcm.signature_authority'
  | 'mrd_hcm.training_curricula'
  | 'mrd_hcm.training_records'
  | 'mrd_erp.bill_of_materials'
  | 'mrd_erp.ingredients'
  | 'mrd_erp.lot_material_consumption'
  | 'mrd_erp.market_authorisations'
  | 'mrd_erp.material_lots'
  | 'mrd_erp.product_lots'
  | 'mrd_erp.products'
  | 'mrd_erp.suppliers'
  | 'mrd_mes.deviations'
  | 'mrd_mes.equipment'
  | 'mrd_mes.equipment_qualification'
  | 'mrd_mes.lines'
  | 'mrd_mes.process_parameters'
  | 'mrd_mes.process_steps'
  | 'mrd_mes.sites'
  | 'mrd_mes.work_orders'
  | 'mrd_qms.audits'
  | 'mrd_qms.batch_dispositions'
  | 'mrd_qms.capas'
  | 'mrd_qms.change_controls'
  | 'mrd_qms.complaints'
  | 'mrd_qms.lab_events'
  | 'mrd_qms.oos_investigations'
  | 'mrd_qms.qc_tests'
  | 'mrd_qms.spec_limits'
  | 'mrd_qms.specification_versions'
  | 'mrd_qms.specifications'
  | 'mrd_qms.test_methods'
  | 'mrd_tms.consignees'
  | 'mrd_tms.drivers'
  | 'mrd_tms.routes'
  | 'mrd_tms.shipment_lines'
  | 'mrd_tms.shipments'
  | 'mrd_tms.telematics_readings'
  | 'mrd_tms.trucks'
  | 'mrd_tms.warehouses'
  | 'mrd_kb.ask_history'
  | 'mrd_kb.document_chunks'
  | 'mrd_kb.document_relations'
  | 'mrd_kb.documents';
