/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DataFlowRouteImport } from './routes/data-flow'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as ApiAssessRouteImport } from './routes/api.assess'
import { Route as ApiExplainRouteImport } from './routes/api.explain'
import { Route as ApiHistoryRouteImport } from './routes/api.history'
import { Route as ApiRequirementsRouteImport } from './routes/api.requirements'
import { Route as ApiSummaryRouteImport } from './routes/api.summary'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataFlowRoute = DataFlowRouteImport.update({
  id: '/data-flow',
  path: '/data-flow',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssessRoute = ApiAssessRouteImport.update({
  id: '/api/assess',
  path: '/api/assess',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExplainRoute = ApiExplainRouteImport.update({
  id: '/api/explain',
  path: '/api/explain',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryRoute = ApiHistoryRouteImport.update({
  id: '/api/history',
  path: '/api/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRequirementsRoute = ApiRequirementsRouteImport.update({
  id: '/api/requirements',
  path: '/api/requirements',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSummaryRoute = ApiSummaryRouteImport.update({
  id: '/api/summary',
  path: '/api/summary',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/data-flow': typeof DataFlowRoute
  '/desk': typeof DeskRoute
  '/api/assess': typeof ApiAssessRoute
  '/api/explain': typeof ApiExplainRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/requirements': typeof ApiRequirementsRoute
  '/api/summary': typeof ApiSummaryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/data-flow': typeof DataFlowRoute
  '/desk': typeof DeskRoute
  '/api/assess': typeof ApiAssessRoute
  '/api/explain': typeof ApiExplainRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/requirements': typeof ApiRequirementsRoute
  '/api/summary': typeof ApiSummaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/data-flow': typeof DataFlowRoute
  '/desk': typeof DeskRoute
  '/api/assess': typeof ApiAssessRoute
  '/api/explain': typeof ApiExplainRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/requirements': typeof ApiRequirementsRoute
  '/api/summary': typeof ApiSummaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/data-flow'
    | '/desk'
    | '/api/assess'
    | '/api/explain'
    | '/api/history'
    | '/api/requirements'
    | '/api/summary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/data-flow'
    | '/desk'
    | '/api/assess'
    | '/api/explain'
    | '/api/history'
    | '/api/requirements'
    | '/api/summary'
  id:
    | '__root__'
    | '/'
    | '/data-flow'
    | '/desk'
    | '/api/assess'
    | '/api/explain'
    | '/api/history'
    | '/api/requirements'
    | '/api/summary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DataFlowRoute: typeof DataFlowRoute
  DeskRoute: typeof DeskRoute
  ApiAssessRoute: typeof ApiAssessRoute
  ApiExplainRoute: typeof ApiExplainRoute
  ApiHistoryRoute: typeof ApiHistoryRoute
  ApiRequirementsRoute: typeof ApiRequirementsRoute
  ApiSummaryRoute: typeof ApiSummaryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-flow': {
      id: '/data-flow'
      path: '/data-flow'
      fullPath: '/data-flow'
      preLoaderRoute: typeof DataFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assess': {
      id: '/api/assess'
      path: '/api/assess'
      fullPath: '/api/assess'
      preLoaderRoute: typeof ApiAssessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/explain': {
      id: '/api/explain'
      path: '/api/explain'
      fullPath: '/api/explain'
      preLoaderRoute: typeof ApiExplainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history': {
      id: '/api/history'
      path: '/api/history'
      fullPath: '/api/history'
      preLoaderRoute: typeof ApiHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/requirements': {
      id: '/api/requirements'
      path: '/api/requirements'
      fullPath: '/api/requirements'
      preLoaderRoute: typeof ApiRequirementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/summary': {
      id: '/api/summary'
      path: '/api/summary'
      fullPath: '/api/summary'
      preLoaderRoute: typeof ApiSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DataFlowRoute: DataFlowRoute,
  DeskRoute: DeskRoute,
  ApiAssessRoute: ApiAssessRoute,
  ApiExplainRoute: ApiExplainRoute,
  ApiHistoryRoute: ApiHistoryRoute,
  ApiRequirementsRoute: ApiRequirementsRoute,
  ApiSummaryRoute: ApiSummaryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
