/**
 * GENERATED by `pnpm recalls:estate` — do not edit.
 *
 * Calder Safety's estate is three tab-delimited files published by NHTSA, not
 * three databases. Column names are transcribed from the agency's own data
 * dictionaries and the count is asserted against the data; see
 * `scripts/estate.mjs` for why that assertion is the load-bearing part.
 *
 * WHERE A VALUE IS MISSING IT SAYS WHY. This is the first corpus on this site
 * made of real people's records, so a column either carries a value read from
 * the file or carries the reason it is not published. Neither is a default.
 */

export interface EstateColumn {
  name: string;
  /** One real value from the file. Absent where the column may not be shown. */
  sample?: string;
  /** Why this column's values are not published. Mutually exclusive with `sample`. */
  withheld?: string;
  /** Percent of rows in which this column is non-empty. */
  filled: number;
  kind: 'text' | 'number' | 'date' | 'flag' | 'json' | 'other';
}

export interface EstateTable {
  name: string;
  columns: EstateColumn[];
  rows: number;
}

export interface EstateSource {
  db: string;
  label: string;
  tables: EstateTable[];
}

/**
 * Every table in the estate, as a union.
 *
 * WHAT IT IS FOR: `estate-notes.ts` types its map against this, so a source
 * added here without a sentence describing it is a FAILING TYPECHECK, and a
 * sentence describing a source that has gone is too. The pages' prose cannot
 * quietly fall behind the data.
 */
export type EstateTableKey = "complaints.CMPL_SLICE" | "recalls.RCL_SLICE" | "investigations.INV_SLICE";

/** The day the snapshot was taken. It is frozen: `FLAT_CMPL.zip` changes daily. */
export const MEASURED_AT = '2026-09-17';

/** The command that reproduces every number in this file. */
export const MEASURED_BY = 'pnpm recalls:estate';

/**
 * ROWS AND UNITS OF MEANING ARE NOT THE SAME NUMBER, and the gap is 44%.
 * NHTSA writes one complaint row per component, so one filing appears up to
 * five times; one recall campaign fans out across every make, model and year it
 * covers. Quoting rows as the size of the estate overstates it.
 */
export const ROWS = {
  "complaints": 100980,
  "recalls": 44791,
  "investigations": 1631
} as const;

export const UNITS = {
  "complaints": 70194,
  "recalls": 3026,
  "investigations": 114
} as const;

export const TOTAL_ROWS = 147402;
export const TOTAL_UNITS = 73334;

export const ESTATE: EstateSource[] = [
  {
    "db": "complaints",
    "label": "FLAT_CMPL",
    "tables": [
      {
        "name": "CMPL_SLICE",
        "rows": 100980,
        "columns": [
          {
            "name": "CMPLID",
            "kind": "number",
            "filled": 100,
            "sample": "1459791"
          },
          {
            "name": "ODINO",
            "kind": "number",
            "filled": 100,
            "sample": "11083622"
          },
          {
            "name": "MFR_NAME",
            "kind": "text",
            "filled": 100,
            "sample": "Volvo Car USA, LLC"
          },
          {
            "name": "MAKETXT",
            "kind": "text",
            "filled": 100,
            "sample": "VOLVO"
          },
          {
            "name": "MODELTXT",
            "kind": "text",
            "filled": 100,
            "sample": "XC40"
          },
          {
            "name": "YEARTXT",
            "kind": "text",
            "filled": 100,
            "sample": "2019"
          },
          {
            "name": "CRASH",
            "kind": "flag",
            "filled": 100,
            "sample": "N"
          },
          {
            "name": "FAILDATE",
            "kind": "date",
            "filled": 100,
            "withheld": "identifies a person"
          },
          {
            "name": "FIRE",
            "kind": "flag",
            "filled": 100,
            "sample": "N"
          },
          {
            "name": "INJURED",
            "kind": "number",
            "filled": 100,
            "sample": "0"
          },
          {
            "name": "DEATHS",
            "kind": "number",
            "filled": 100,
            "sample": "0"
          },
          {
            "name": "COMPDESC",
            "kind": "text",
            "filled": 100,
            "sample": "SEATS"
          },
          {
            "name": "CITY",
            "kind": "text",
            "filled": 100,
            "withheld": "identifies a person"
          },
          {
            "name": "STATE",
            "kind": "text",
            "filled": 100,
            "withheld": "identifies a person"
          },
          {
            "name": "VIN",
            "kind": "text",
            "filled": 99,
            "withheld": "identifies a person"
          },
          {
            "name": "DATEA",
            "kind": "date",
            "filled": 100,
            "sample": "20180406"
          },
          {
            "name": "LDATE",
            "kind": "date",
            "filled": 100,
            "sample": "20180406"
          },
          {
            "name": "MILES",
            "kind": "number",
            "filled": 32,
            "withheld": "identifies a person"
          },
          {
            "name": "OCCURENCES",
            "kind": "number",
            "filled": 2,
            "sample": "3"
          },
          {
            "name": "CDESCR",
            "kind": "text",
            "filled": 100,
            "withheld": "their own words"
          },
          {
            "name": "CMPL_TYPE",
            "kind": "other",
            "filled": 100,
            "sample": "IVOQ"
          },
          {
            "name": "POLICE_RPT_YN",
            "kind": "flag",
            "filled": 100,
            "sample": "N"
          },
          {
            "name": "PURCH_DT",
            "kind": "date",
            "filled": 0,
            "withheld": "identifies a person"
          },
          {
            "name": "ORIG_OWNER_YN",
            "kind": "flag",
            "filled": 100,
            "sample": "N"
          },
          {
            "name": "ANTI_BRAKES_YN",
            "kind": "flag",
            "filled": 100,
            "sample": "N"
          },
          {
            "name": "CRUISE_CONT_YN",
            "kind": "flag",
            "filled": 100,
            "sample": "N"
          },
          {
            "name": "NUM_CYLS",
            "kind": "number",
            "filled": 4,
            "sample": "4"
          },
          {
            "name": "DRIVE_TRAIN",
            "kind": "other",
            "filled": 4,
            "sample": "FWD"
          },
          {
            "name": "FUEL_SYS",
            "kind": "other",
            "filled": 0,
            "sample": "FI"
          },
          {
            "name": "FUEL_TYPE",
            "kind": "other",
            "filled": 4,
            "sample": "GS"
          },
          {
            "name": "TRANS_TYPE",
            "kind": "other",
            "filled": 0,
            "sample": "AUTO"
          },
          {
            "name": "VEH_SPEED",
            "kind": "number",
            "filled": 55,
            "sample": "0"
          },
          {
            "name": "DOT",
            "kind": "text",
            "filled": 0,
            "withheld": "identifies a person"
          },
          {
            "name": "TIRE_SIZE",
            "kind": "text",
            "filled": 0
          },
          {
            "name": "LOC_OF_TIRE",
            "kind": "other",
            "filled": 0
          },
          {
            "name": "TIRE_FAIL_TYPE",
            "kind": "other",
            "filled": 0
          },
          {
            "name": "ORIG_EQUIP_YN",
            "kind": "flag",
            "filled": 0,
            "sample": "N"
          },
          {
            "name": "MANUF_DT",
            "kind": "date",
            "filled": 0,
            "sample": "20210401"
          },
          {
            "name": "SEAT_TYPE",
            "kind": "other",
            "filled": 0,
            "sample": "C"
          },
          {
            "name": "RESTRAINT_TYPE",
            "kind": "other",
            "filled": 0,
            "sample": "E"
          },
          {
            "name": "DEALER_NAME",
            "kind": "text",
            "filled": 9,
            "withheld": "a dealer’s details"
          },
          {
            "name": "DEALER_TEL",
            "kind": "text",
            "filled": 4,
            "withheld": "a dealer’s details"
          },
          {
            "name": "DEALER_CITY",
            "kind": "text",
            "filled": 9,
            "withheld": "a dealer’s details"
          },
          {
            "name": "DEALER_STATE",
            "kind": "text",
            "filled": 9,
            "withheld": "a dealer’s details"
          },
          {
            "name": "DEALER_ZIP",
            "kind": "text",
            "filled": 8,
            "withheld": "a dealer’s details"
          },
          {
            "name": "PROD_TYPE",
            "kind": "other",
            "filled": 100,
            "sample": "V"
          },
          {
            "name": "REPAIRED_YN",
            "kind": "flag",
            "filled": 0
          },
          {
            "name": "MEDICAL_ATTN",
            "kind": "flag",
            "filled": 100,
            "sample": "N"
          },
          {
            "name": "VEHICLES_TOWED_YN",
            "kind": "flag",
            "filled": 100,
            "sample": "N"
          },
          {
            "name": "STATE_OF_INCIDENT",
            "kind": "text",
            "filled": 8,
            "withheld": "identifies a person"
          },
          {
            "name": "VEHICLE_OPERATOR",
            "kind": "text",
            "filled": 0,
            "withheld": "identifies a person"
          }
        ]
      }
    ]
  },
  {
    "db": "recalls",
    "label": "FLAT_RCL_POST_2010",
    "tables": [
      {
        "name": "RCL_SLICE",
        "rows": 44791,
        "columns": [
          {
            "name": "RECORD_ID",
            "kind": "number",
            "filled": 100,
            "sample": "129250"
          },
          {
            "name": "CAMPNO",
            "kind": "text",
            "filled": 100,
            "sample": "17V510000"
          },
          {
            "name": "MAKETXT",
            "kind": "text",
            "filled": 100,
            "sample": "BLUE BIRD"
          },
          {
            "name": "MODELTXT",
            "kind": "text",
            "filled": 100,
            "sample": "VISION"
          },
          {
            "name": "YEARTXT",
            "kind": "text",
            "filled": 100,
            "sample": "2019"
          },
          {
            "name": "MFGCAMPNO",
            "kind": "text",
            "filled": 91,
            "sample": "R17ZB-SB"
          },
          {
            "name": "COMPNAME",
            "kind": "text",
            "filled": 100,
            "sample": "SEATS"
          },
          {
            "name": "MFGNAME",
            "kind": "text",
            "filled": 100,
            "sample": "Blue Bird Body Company"
          },
          {
            "name": "BGMAN",
            "kind": "date",
            "filled": 12,
            "sample": "20140718"
          },
          {
            "name": "ENDMAN",
            "kind": "date",
            "filled": 10,
            "sample": "20170719"
          },
          {
            "name": "RCLTYPECD",
            "kind": "other",
            "filled": 100,
            "sample": "V"
          },
          {
            "name": "POTAFF",
            "kind": "number",
            "filled": 100,
            "sample": "309"
          },
          {
            "name": "ODATE",
            "kind": "date",
            "filled": 99,
            "sample": "20170915"
          },
          {
            "name": "INFLUENCED_BY",
            "kind": "other",
            "filled": 100,
            "sample": "MFR"
          },
          {
            "name": "MFGTXT",
            "kind": "text",
            "filled": 100,
            "sample": "Blue Bird Body Company"
          },
          {
            "name": "RCDATE",
            "kind": "date",
            "filled": 100,
            "sample": "20170817"
          },
          {
            "name": "DATEA",
            "kind": "date",
            "filled": 100,
            "sample": "20170818"
          },
          {
            "name": "RPNO",
            "kind": "other",
            "filled": 0
          },
          {
            "name": "FMVSS",
            "kind": "other",
            "filled": 18,
            "sample": "210"
          },
          {
            "name": "DESC_DEFECT",
            "kind": "text",
            "filled": 100,
            "sample": "Blue Bird Body Company (Blue Bird) is recalling certa…"
          },
          {
            "name": "CONEQUENCE_DEFECT",
            "kind": "text",
            "filled": 100,
            "sample": "In a rear crash event, the occupant's head may contac…"
          },
          {
            "name": "CORRECTIVE_ACTION",
            "kind": "text",
            "filled": 100,
            "sample": "Blue Bird will notify owners, and dealers will equip …"
          },
          {
            "name": "NOTES",
            "kind": "text",
            "filled": 96,
            "sample": "Owners may also contact the National Highway Traffic …"
          },
          {
            "name": "RCL_CMPT_ID",
            "kind": "text",
            "filled": 100,
            "sample": "000074167002733718000000318"
          },
          {
            "name": "MFR_COMP_NAME",
            "kind": "text",
            "filled": 89,
            "sample": "Driver Airbag"
          },
          {
            "name": "MFR_COMP_DESC",
            "kind": "text",
            "filled": 87,
            "sample": "Driver Airbag"
          },
          {
            "name": "MFR_COMP_PTNO",
            "kind": "text",
            "filled": 87,
            "sample": "A000 860 77 01 9116"
          },
          {
            "name": "DO_NOT_DRIVE",
            "kind": "flag",
            "filled": 100,
            "sample": "No"
          },
          {
            "name": "PARK_OUTSIDE",
            "kind": "flag",
            "filled": 100,
            "sample": "No"
          }
        ]
      }
    ]
  },
  {
    "db": "investigations",
    "label": "FLAT_INV",
    "tables": [
      {
        "name": "INV_SLICE",
        "rows": 1631,
        "columns": [
          {
            "name": "NHTSA_ACTION_NUMBER",
            "kind": "text",
            "filled": 100,
            "sample": "AQ22003"
          },
          {
            "name": "MAKE",
            "kind": "text",
            "filled": 100,
            "sample": "NISSAN"
          },
          {
            "name": "MODEL",
            "kind": "text",
            "filled": 100,
            "sample": "ALTIMA"
          },
          {
            "name": "YEAR",
            "kind": "text",
            "filled": 100,
            "sample": "2019"
          },
          {
            "name": "COMPNAME",
            "kind": "text",
            "filled": 100,
            "sample": "LATCHES/LOCKS/LINKAGES:HOOD:LATCH"
          },
          {
            "name": "MFR_NAME",
            "kind": "text",
            "filled": 100,
            "sample": "Nissan North America, Inc."
          },
          {
            "name": "ODATE",
            "kind": "date",
            "filled": 100,
            "sample": "20221216"
          },
          {
            "name": "CDATE",
            "kind": "date",
            "filled": 84,
            "sample": "20190917"
          },
          {
            "name": "CAMPNO",
            "kind": "text",
            "filled": 48,
            "sample": "22V063000"
          },
          {
            "name": "SUBJECT",
            "kind": "text",
            "filled": 100,
            "sample": "Hertz/Vehicles Rented with Open Recalls"
          },
          {
            "name": "SUMMARY",
            "kind": "text",
            "filled": 100,
            "sample": "NHTSA is opening this audit query to investigate whet…"
          }
        ]
      }
    ]
  }
];

/**
 * WHAT IS IN THE NARRATIVES AND WHAT HAPPENED TO THE PEOPLE IN THEM.
 *
 * COUNTED PER COMPLAINT, NOT PER ROW. `docs/recalls/CORPUS.md` §3 and §5 count
 * the same things per row, so its figures are these facts multiplied by the
 * component fan-out. Both are honest; only one can be called "complaints that
 * report a death", and it is this one.
 */
export const COMPLAINT_FACTS = {
  "crash": 2729,
  "fire": 843,
  "injured": 1721,
  "deaths": 41,
  "fatalities": 53,
  "allCaps": 16292,
  "short": 1150
} as const;

export const DISTINCT = {
  "makes": 198,
  "makeModel": 988,
  "components": 472
} as const;

/**
 * `INFLUENCED_BY` — who started the recall, PER CAMPAIGN.
 *
 * The one conflict in this estate that needs no inference: NHTSA writes down
 * whether the manufacturer volunteered or was pushed into it.
 */
export const INFLUENCED_BY: Record<string, number> = {
  "MFR": 2893,
  "ODI": 107,
  "OVSC": 26
};
