/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DataFlowRouteImport } from './routes/data-flow'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as StepsRouteImport } from './routes/steps'
import { Route as ApiAskRouteImport } from './routes/api.ask'
import { Route as ApiEnginesRouteImport } from './routes/api.engines'
import { Route as ApiHistoryRouteImport } from './routes/api.history'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataFlowRoute = DataFlowRouteImport.update({
  id: '/data-flow',
  path: '/data-flow',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const StepsRoute = StepsRouteImport.update({
  id: '/steps',
  path: '/steps',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAskRoute = ApiAskRouteImport.update({
  id: '/api/ask',
  path: '/api/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEnginesRoute = ApiEnginesRouteImport.update({
  id: '/api/engines',
  path: '/api/engines',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryRoute = ApiHistoryRouteImport.update({
  id: '/api/history',
  path: '/api/history',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/data-flow': typeof DataFlowRoute
  '/desk': typeof DeskRoute
  '/steps': typeof StepsRoute
  '/api/ask': typeof ApiAskRoute
  '/api/engines': typeof ApiEnginesRoute
  '/api/history': typeof ApiHistoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/data-flow': typeof DataFlowRoute
  '/desk': typeof DeskRoute
  '/steps': typeof StepsRoute
  '/api/ask': typeof ApiAskRoute
  '/api/engines': typeof ApiEnginesRoute
  '/api/history': typeof ApiHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/data-flow': typeof DataFlowRoute
  '/desk': typeof DeskRoute
  '/steps': typeof StepsRoute
  '/api/ask': typeof ApiAskRoute
  '/api/engines': typeof ApiEnginesRoute
  '/api/history': typeof ApiHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/data-flow'
    | '/desk'
    | '/steps'
    | '/api/ask'
    | '/api/engines'
    | '/api/history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/data-flow'
    | '/desk'
    | '/steps'
    | '/api/ask'
    | '/api/engines'
    | '/api/history'
  id:
    | '__root__'
    | '/'
    | '/data-flow'
    | '/desk'
    | '/steps'
    | '/api/ask'
    | '/api/engines'
    | '/api/history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DataFlowRoute: typeof DataFlowRoute
  DeskRoute: typeof DeskRoute
  StepsRoute: typeof StepsRoute
  ApiAskRoute: typeof ApiAskRoute
  ApiEnginesRoute: typeof ApiEnginesRoute
  ApiHistoryRoute: typeof ApiHistoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-flow': {
      id: '/data-flow'
      path: '/data-flow'
      fullPath: '/data-flow'
      preLoaderRoute: typeof DataFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/steps': {
      id: '/steps'
      path: '/steps'
      fullPath: '/steps'
      preLoaderRoute: typeof StepsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ask': {
      id: '/api/ask'
      path: '/api/ask'
      fullPath: '/api/ask'
      preLoaderRoute: typeof ApiAskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/engines': {
      id: '/api/engines'
      path: '/api/engines'
      fullPath: '/api/engines'
      preLoaderRoute: typeof ApiEnginesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history': {
      id: '/api/history'
      path: '/api/history'
      fullPath: '/api/history'
      preLoaderRoute: typeof ApiHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DataFlowRoute: DataFlowRoute,
  DeskRoute: DeskRoute,
  StepsRoute: StepsRoute,
  ApiAskRoute: ApiAskRoute,
  ApiEnginesRoute: ApiEnginesRoute,
  ApiHistoryRoute: ApiHistoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
