/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DataFlowRouteImport } from './routes/data-flow'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as SupplierRouteImport } from './routes/supplier'
import { Route as ApiAskRouteImport } from './routes/api.ask'
import { Route as ApiHistoryRouteImport } from './routes/api.history'
import { Route as ApiLotsRouteImport } from './routes/api.lots'
import { Route as ApiSupplierRouteImport } from './routes/api.supplier'
import { Route as ApiSuppliersRouteImport } from './routes/api.suppliers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataFlowRoute = DataFlowRouteImport.update({
  id: '/data-flow',
  path: '/data-flow',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierRoute = SupplierRouteImport.update({
  id: '/supplier',
  path: '/supplier',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAskRoute = ApiAskRouteImport.update({
  id: '/api/ask',
  path: '/api/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryRoute = ApiHistoryRouteImport.update({
  id: '/api/history',
  path: '/api/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLotsRoute = ApiLotsRouteImport.update({
  id: '/api/lots',
  path: '/api/lots',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSupplierRoute = ApiSupplierRouteImport.update({
  id: '/api/supplier',
  path: '/api/supplier',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSuppliersRoute = ApiSuppliersRouteImport.update({
  id: '/api/suppliers',
  path: '/api/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/data-flow': typeof DataFlowRoute
  '/desk': typeof DeskRoute
  '/supplier': typeof SupplierRoute
  '/api/ask': typeof ApiAskRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/lots': typeof ApiLotsRoute
  '/api/supplier': typeof ApiSupplierRoute
  '/api/suppliers': typeof ApiSuppliersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/data-flow': typeof DataFlowRoute
  '/desk': typeof DeskRoute
  '/supplier': typeof SupplierRoute
  '/api/ask': typeof ApiAskRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/lots': typeof ApiLotsRoute
  '/api/supplier': typeof ApiSupplierRoute
  '/api/suppliers': typeof ApiSuppliersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/data-flow': typeof DataFlowRoute
  '/desk': typeof DeskRoute
  '/supplier': typeof SupplierRoute
  '/api/ask': typeof ApiAskRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/lots': typeof ApiLotsRoute
  '/api/supplier': typeof ApiSupplierRoute
  '/api/suppliers': typeof ApiSuppliersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/data-flow'
    | '/desk'
    | '/supplier'
    | '/api/ask'
    | '/api/history'
    | '/api/lots'
    | '/api/supplier'
    | '/api/suppliers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/data-flow'
    | '/desk'
    | '/supplier'
    | '/api/ask'
    | '/api/history'
    | '/api/lots'
    | '/api/supplier'
    | '/api/suppliers'
  id:
    | '__root__'
    | '/'
    | '/data-flow'
    | '/desk'
    | '/supplier'
    | '/api/ask'
    | '/api/history'
    | '/api/lots'
    | '/api/supplier'
    | '/api/suppliers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DataFlowRoute: typeof DataFlowRoute
  DeskRoute: typeof DeskRoute
  SupplierRoute: typeof SupplierRoute
  ApiAskRoute: typeof ApiAskRoute
  ApiHistoryRoute: typeof ApiHistoryRoute
  ApiLotsRoute: typeof ApiLotsRoute
  ApiSupplierRoute: typeof ApiSupplierRoute
  ApiSuppliersRoute: typeof ApiSuppliersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-flow': {
      id: '/data-flow'
      path: '/data-flow'
      fullPath: '/data-flow'
      preLoaderRoute: typeof DataFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier': {
      id: '/supplier'
      path: '/supplier'
      fullPath: '/supplier'
      preLoaderRoute: typeof SupplierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ask': {
      id: '/api/ask'
      path: '/api/ask'
      fullPath: '/api/ask'
      preLoaderRoute: typeof ApiAskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history': {
      id: '/api/history'
      path: '/api/history'
      fullPath: '/api/history'
      preLoaderRoute: typeof ApiHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lots': {
      id: '/api/lots'
      path: '/api/lots'
      fullPath: '/api/lots'
      preLoaderRoute: typeof ApiLotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/supplier': {
      id: '/api/supplier'
      path: '/api/supplier'
      fullPath: '/api/supplier'
      preLoaderRoute: typeof ApiSupplierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/suppliers': {
      id: '/api/suppliers'
      path: '/api/suppliers'
      fullPath: '/api/suppliers'
      preLoaderRoute: typeof ApiSuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DataFlowRoute: DataFlowRoute,
  DeskRoute: DeskRoute,
  SupplierRoute: SupplierRoute,
  ApiAskRoute: ApiAskRoute,
  ApiHistoryRoute: ApiHistoryRoute,
  ApiLotsRoute: ApiLotsRoute,
  ApiSupplierRoute: ApiSupplierRoute,
  ApiSuppliersRoute: ApiSuppliersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
