/**
 * GENERATED by `pnpm steering:corpus-web` — do not edit.
 *
 * What is in the customer's files: how many, how big, and the first fourteen
 * lines of one real file per group. The prose about what each group IS and what
 * makes it hard to read is written by hand in the generator, because that is a
 * judgement; everything numeric here was counted.
 */

export interface CorpusExample {
  path: string;
  lines: string[];
}

export interface CorpusGroup {
  id: string;
  name: string;
  what: string;
  /** The thing that makes it hard to read. */
  snag: string;
  /** The `vst_derived` table this becomes, or '' where nothing reads it yet. */
  produces: string;
  files: number;
  bytes: number;
  kinds: Array<{ ext: string; n: number }>;
  example: CorpusExample;
}

/** The day the files were counted. */
export const MEASURED_AT = '2026-09-13';

/** The command that reproduces every number here. */
export const MEASURED_BY = 'pnpm steering:corpus-web';

export const TOTAL_FILES = 1069;
export const TOTAL_BYTES = 1989829;

export const CORPUS: CorpusGroup[] = [
  {
    "id": "timesheets",
    "name": "Timesheets",
    "what": "Quarterly exports from the time-booking system.",
    "produces": "timesheet_lines",
    "files": 25,
    "bytes": 460564,
    "kinds": [
      {
        "ext": "csv",
        "n": 25
      }
    ],
    "example": {
      "path": "pmo/timesheets/2023-Q2.csv",
      "lines": [
        "# Vantis Steering Systems — timesheet export",
        "# period: 2023 Q2   exported: 2023-07-05",
        "# charge code format changed in 2022 and again in 2024. Older rows keep the old format.",
        "# an empty 'approved' column means the line was never signed off, not that it was rejected.",
        "week_ending,employee,charge_code,hours,activity,approved",
        "2023-04-01,L. Renaud,VST1006,37.0,safety,Y",
        "2023-04-08,I. Arnaud,VST1006,20.0,safety,Y",
        "2023-04-15,L. Renaud,VST1006,10.0,safety,Y",
        "2023-04-22,\"Dietrich, Rea\",VST1006,5.0,safety,Y",
        "2023-04-01,A. Kovac,VST1006,32.0,safety,Y",
        "2023-05-08,\"Lindqvist, Maja\",VST1006,8.0,safety,Y",
        "2023-05-15,\"Ferreira, Diogo\",VST1006,28.0,safety,Y",
        "2023-05-22,N. Haas,VST1006,19.0,safety,Y",
        "2023-05-01,A. Kovac,VST1006,19.0,safety,Y"
      ]
    },
    "snag": "Three quarters were never exported. The charge-code format changed twice. One name is quoted with a comma inside it, and twelve people are spelled two ways."
  },
  {
    "id": "closure-reports",
    "name": "Closure reports",
    "what": "What a completed piece of work was, written up when it closed.",
    "produces": "document_fields",
    "files": 220,
    "bytes": 198337,
    "kinds": [
      {
        "ext": "md",
        "n": 220
      }
    ],
    "example": {
      "path": "pmo/closure-reports/EFF-2021-0443.md",
      "lines": [
        "PROJECT CLOSURE REPORT",
        "Vantis Steering Systems — Programme Office",
        "",
        "Reference:     EFF-2021-0443",
        "Charge code:   1000",
        "Programme:     PRG-HLX-H1  (H1, R-EPS)",
        "Change ref:    none — standing work",
        "Completed:     2021-11-26",
        "Region:        EU",
        "Prepared by:   I. Arnaud, 2023-02-25",
        "",
        "1. WHAT WAS DONE",
        "",
        "   Gearbox housing change, H1 facelift."
      ]
    },
    "snag": "The head block is regular and parses. Everything a reader actually wants — why the hours were what they were, whether a safety case was involved — is in prose underneath it."
  },
  {
    "id": "quotes",
    "name": "Quotations",
    "what": "What was quoted to a customer, line by line.",
    "produces": "quote_line_items",
    "files": 52,
    "bytes": 46327,
    "kinds": [
      {
        "ext": "md",
        "n": 52
      }
    ],
    "example": {
      "path": "pmo/quotes/QUO-0044.md",
      "lines": [
        "# Quotation QUO-0044",
        "**RFQ:** RFQ-2020-0043 · **Programme:** PRG-VGR-24 (Gale)",
        "**Issued:** 2021-09-06 · **Outcome:** won",
        "",
        "## Engineering effort",
        "",
        "| # | description | class | hours |",
        "|---|---|---|---|",
        "| 1 | recalibrate on Gale | recalibrate | 135.6 |",
        "| 2 | integration only on Gale | integration_only | 126 |",
        "| 3 | safety case only on Gale | safety_case_only | 216 |",
        "| 4 | safety case only on Gale | safety_case_only | 280 |",
        "| 5 | modify function on Gale | modify_function | 336 |",
        "| 6 | safety case only on Gale | safety_case_only | 356 |"
      ]
    },
    "snag": "The table and the bold total parse exactly. The Assumptions section below is prose. No quotation names the requirement a line priced."
  },
  {
    "id": "estimates",
    "name": "Estimates",
    "what": "Bottom-up estimates, by work package and discipline.",
    "produces": "estimate_lines",
    "files": 34,
    "bytes": 20887,
    "kinds": [
      {
        "ext": "csv",
        "n": 34
      }
    ],
    "example": {
      "path": "pmo/estimates/PRG-KAI-22-estimate.csv",
      "lines": [
        "# bottom-up estimate, built before nomination",
        "# author: N. Haas   date: 2022-05-24",
        "# \"basis\" is free text. It is the only record of WHERE a number came from.",
        "work_package,discipline,hours,basis,confidence",
        "HIL rig update,pm,505,from the last programme,low",
        "safety case,calibration,399,supplier quote,medium",
        "EOL calibration,systems,51,guess,medium",
        "safety case,pm,267,similar to H1,low",
        "validation,hardware,438,supplier quote,medium",
        "EOL calibration,safety,314,similar to H1,medium",
        "HIL rig update,validation,148,supplier quote,medium",
        "EOL calibration,hardware,495,similar to H1,medium",
        "EOL calibration,calibration,315,similar to H1,low",
        "diagnostics,validation,466,supplier quote,high"
      ]
    },
    "snag": "Every line carries how it was arrived at — a supplier quote, the last programme, engineering judgement, or a guess. Sixty-six of them are guesses."
  },
  {
    "id": "rate-cards",
    "name": "Rate cards",
    "what": "What an hour of each discipline costs.",
    "produces": "rate_card_lines",
    "files": 24,
    "bytes": 8214,
    "kinds": [
      {
        "ext": "csv",
        "n": 24
      }
    ],
    "example": {
      "path": "pmo/rate-cards/2025-NA.csv",
      "lines": [
        "# Vantis Steering Systems — approved engineering rates",
        "# year: 2025   region: NA",
        "# approved by: M. Lindqvist (finance)   date: 2024-11-21",
        "# rates are fully loaded and include overhead. Do not add a multiplier.",
        "discipline,rate_eur_per_hour",
        "systems,135.26",
        "software,129.63",
        "hardware,132.44",
        "calibration,121.17",
        "validation,109.90",
        "safety,152.17",
        "pm,143.72",
        ""
      ]
    },
    "snag": "Seven rows of discipline and rate. Which year and which region they apply to is not in the data at all — it is in a comment above the header, and in the filename."
  },
  {
    "id": "requirements",
    "name": "Requirements",
    "what": "Customer specifications at each revision, trace matrices, architecture notes, review notes.",
    "produces": "",
    "files": 212,
    "bytes": 665080,
    "kinds": [
      {
        "ext": "md",
        "n": 174
      },
      {
        "ext": "csv",
        "n": 38
      }
    ],
    "example": {
      "path": "requirements/PRG-TDR-01/system-requirements-PRG-TDR-01.md",
      "lines": [
        "# System Requirements Specification — Delve",
        "**Internal document** · Vantis Steering Systems · Revision 4",
        "**Derived from:** CRS-TDR-01-001 Rev C",
        "**Owner:** systems engineering",
        "",
        "## 1. Purpose",
        "",
        "Transforms the customer requirements in CRS-TDR-01-001 into requirements on",
        "the Vantis system. Every requirement below either traces to a customer",
        "requirement or is marked DERIVED with its rationale.",
        "",
        "## 2. Requirements",
        "",
        "### SR-TDR-01-0023 — nvh limit db"
      ]
    },
    "snag": "Rev A and Rev B of the same spec disagree, on purpose. One requirement is stated twice with different numbers. Forces are written three ways, including one with no space before the unit."
  },
  {
    "id": "code",
    "name": "Source repositories",
    "what": "Eight repositories: sources, headers, tests, MISRA reports, design docs, a git log dump.",
    "produces": "",
    "files": 477,
    "bytes": 556737,
    "kinds": [
      {
        "ext": "md",
        "n": 151
      },
      {
        "ext": "c",
        "n": 147
      },
      {
        "ext": "txt",
        "n": 81
      },
      {
        "ext": "h",
        "n": 73
      },
      {
        "ext": "—",
        "n": 16
      },
      {
        "ext": "json",
        "n": 8
      },
      {
        "ext": "csv",
        "n": 1
      }
    ],
    "example": {
      "path": "eps-steering-feel/docs/safety-assessment-2021.md",
      "lines": [
        "",
        "# Safety assessment — steering feel components",
        "**Document:** VST-SA-2021-014 · **Revision:** 3 · **Date:** 2021-10-08",
        "**Author:** a.kovac (functional safety) · **Status:** released",
        "",
        "## 1. Scope",
        "",
        "This assessment covers the four steering feel components as integrated on the",
        "H1 platform (R-EPS, 7600 N class). It does not cover the arbitration or safety",
        "monitor components, which are assessed separately in VST-SA-2020-009.",
        "",
        "## 2. Hazard analysis summary",
        "",
        "The relevant vehicle-level hazard is unintended lateral motion arising from"
      ]
    },
    "snag": "The safety level of one module is stated in three places that disagree, and the only explanation is a paragraph in a MISRA deviation. One file in 1,069 names a part number."
  },
  {
    "id": "releases",
    "name": "Releases and tickets",
    "what": "Release notes per version, and one export from the ticket system.",
    "produces": "",
    "files": 25,
    "bytes": 33683,
    "kinds": [
      {
        "ext": "md",
        "n": 24
      },
      {
        "ext": "csv",
        "n": 1
      }
    ],
    "example": {
      "path": "releases/eps-steering-feel-2.0.9.md",
      "lines": [
        "",
        "# eps-steering-feel 2.0.9",
        "**Released:** 2020-11-11 · **Status:** released",
        "**Programmes:** PRG-KAI-34, PRG-HLX-14, PRG-ALT-08",
        "",
        "## What changed",
        "",
        "Calibration range widened following the customer ride evaluation.",
        "",
        "## Known limitations",
        "",
        "The compatibility shim for the pre-2018 symbol name is still present.",
        ""
      ]
    },
    "snag": "A ticket export is one CSV with free text in the field that matters."
  }
];
