/**
 * GENERATED by `pnpm steering:estate` — do not edit.
 *
 * Every table in the estate — the customer's four systems of record AND
 * `vst_derived`, which is ours — its columns, and an exact row count as of
 * the date below. The prose about what each table HOLDS is not here: it is
 * hand-written in `estate-notes.ts`, typed against `EstateTableKey`, so a
 * table added without a note fails `pnpm typecheck`.
 */

export interface EstateColumn {
  name: string;
  /** One real value from the table, truncated. Absent for empty tables. */
  sample?: string;
  kind: 'text' | 'number' | 'date' | 'flag' | 'json' | 'other';
}

export interface EstateTable {
  name: string;
  columns: EstateColumn[];
  rows: number;
}

export interface EstateSystem {
  db: string;
  label: string;
  /** False for `vst_derived`. It is a knowledge base we built, not a system they run. */
  isSystemOfRecord: boolean;
  /** The commercial tool this stands in for, as the customer would name it. */
  standsFor: string;
  tables: EstateTable[];
}

/** The day the counts were measured. Printed on the page beside them. */
export const MEASURED_AT = '2026-09-13';

/** The command that reproduces every number in this file. */
export const MEASURED_BY = 'pnpm steering:estate';

export const TOTAL_ROWS = 32853;

export const ESTATE: EstateSystem[] = [
  {
    "db": "vst_crm",
    "label": "customers & programmes",
    "isSystemOfRecord": true,
    "standsFor": "Salesforce",
    "tables": [
      {
        "name": "contacts",
        "columns": [
          {
            "name": "contact_id",
            "kind": "text",
            "sample": "CON-0001"
          },
          {
            "name": "customer_id",
            "kind": "text",
            "sample": "CUS-KST"
          },
          {
            "name": "full_name",
            "kind": "text",
            "sample": "Nadia Beker"
          },
          {
            "name": "role",
            "kind": "text",
            "sample": "programme management"
          },
          {
            "name": "email",
            "kind": "text",
            "sample": "Nadia.Beker@kestrel.examp…"
          }
        ],
        "rows": 59
      },
      {
        "name": "customers",
        "columns": [
          {
            "name": "customer_id",
            "kind": "text",
            "sample": "CUS-ALT"
          },
          {
            "name": "name",
            "kind": "text",
            "sample": "Altura Mobility"
          },
          {
            "name": "country",
            "kind": "text",
            "sample": "ES"
          },
          {
            "name": "kind",
            "kind": "text",
            "sample": "OEM"
          },
          {
            "name": "relationship_since",
            "kind": "date",
            "sample": "2005-09-09"
          }
        ],
        "rows": 11
      },
      {
        "name": "milestones",
        "columns": [
          {
            "name": "milestone_id",
            "kind": "text",
            "sample": "MS-0001"
          },
          {
            "name": "program_id",
            "kind": "text",
            "sample": "PRG-KST-K2"
          },
          {
            "name": "name",
            "kind": "text",
            "sample": "RFQ due"
          },
          {
            "name": "planned_on",
            "kind": "date",
            "sample": "2024-11-01"
          },
          {
            "name": "actual_on",
            "kind": "date",
            "sample": "2024-11-01"
          },
          {
            "name": "status",
            "kind": "text",
            "sample": "met"
          }
        ],
        "rows": 246
      },
      {
        "name": "programs",
        "columns": [
          {
            "name": "program_id",
            "kind": "text",
            "sample": "PRG-ALT-08"
          },
          {
            "name": "customer_id",
            "kind": "text",
            "sample": "CUS-ALT"
          },
          {
            "name": "model",
            "kind": "text",
            "sample": "Calder"
          },
          {
            "name": "segment",
            "kind": "text",
            "sample": "B"
          },
          {
            "name": "eps_architecture",
            "kind": "text",
            "sample": "R-EPS"
          },
          {
            "name": "force_class_n",
            "kind": "number",
            "sample": "7300"
          },
          {
            "name": "region",
            "kind": "text",
            "sample": "CN"
          },
          {
            "name": "sop_on",
            "kind": "date",
            "sample": "2026-03-09"
          },
          {
            "name": "volume_per_year",
            "kind": "number",
            "sample": "214000"
          },
          {
            "name": "status",
            "kind": "text",
            "sample": "production"
          }
        ],
        "rows": 38
      },
      {
        "name": "rfq_specs",
        "columns": [
          {
            "name": "rfq_id",
            "kind": "text",
            "sample": "RFQ-2026-0044"
          },
          {
            "name": "spec_ref",
            "kind": "text",
            "sample": "CRS-KST-K2-001"
          },
          {
            "name": "spec_revision",
            "kind": "text",
            "sample": "Rev B"
          },
          {
            "name": "attached_on",
            "kind": "date",
            "sample": "2026-08-14"
          }
        ],
        "rows": 1
      },
      {
        "name": "rfqs",
        "columns": [
          {
            "name": "rfq_id",
            "kind": "text",
            "sample": "RFQ-2019-0017"
          },
          {
            "name": "customer_id",
            "kind": "text",
            "sample": "CUS-KAI"
          },
          {
            "name": "program_id",
            "kind": "text",
            "sample": "PRG-KAI-34"
          },
          {
            "name": "issued_on",
            "kind": "date",
            "sample": "2020-06-24"
          },
          {
            "name": "due_on",
            "kind": "date",
            "sample": "2020-08-22"
          },
          {
            "name": "status",
            "kind": "text",
            "sample": "lost"
          },
          {
            "name": "decided_on",
            "kind": "date",
            "sample": "2020-12-13"
          },
          {
            "name": "lost_reason",
            "kind": "text",
            "sample": "capacity"
          }
        ],
        "rows": 52
      }
    ]
  },
  {
    "db": "vst_plm",
    "label": "hardware",
    "isSystemOfRecord": true,
    "standsFor": "Windchill / Teamcenter",
    "tables": [
      {
        "name": "assemblies",
        "columns": [
          {
            "name": "assembly_no",
            "kind": "text",
            "sample": "VS-ASM-CEPS-0001"
          },
          {
            "name": "name",
            "kind": "text",
            "sample": "Vantis Column Assist asse…"
          },
          {
            "name": "line_id",
            "kind": "text",
            "sample": "PL-CEPS"
          },
          {
            "name": "revision",
            "kind": "text",
            "sample": "A"
          }
        ],
        "rows": 90
      },
      {
        "name": "bom_lines",
        "columns": [
          {
            "name": "assembly_no",
            "kind": "text",
            "sample": "VS-ASM-CEPS-0001"
          },
          {
            "name": "part_no",
            "kind": "text",
            "sample": "VS-ECU-1707-B"
          },
          {
            "name": "qty",
            "kind": "number",
            "sample": "1"
          },
          {
            "name": "position",
            "kind": "text",
            "sample": "P84"
          }
        ],
        "rows": 599
      },
      {
        "name": "component_suppliers",
        "columns": [
          {
            "name": "supplier_id",
            "kind": "text",
            "sample": "CSUP-01"
          },
          {
            "name": "name",
            "kind": "text",
            "sample": "Norlind Elektronik"
          },
          {
            "name": "country",
            "kind": "text",
            "sample": "SE"
          },
          {
            "name": "status",
            "kind": "text",
            "sample": "approved"
          },
          {
            "name": "approved_on",
            "kind": "date",
            "sample": "2020-08-14"
          }
        ],
        "rows": 12
      },
      {
        "name": "part_capabilities",
        "columns": [
          {
            "name": "part_no",
            "kind": "text",
            "sample": "VS-ECU-1021-D"
          },
          {
            "name": "attribute",
            "kind": "text",
            "sample": "cont_current_a"
          },
          {
            "name": "value",
            "kind": "number",
            "sample": "102.600"
          },
          {
            "name": "unit",
            "kind": "text",
            "sample": "A"
          },
          {
            "name": "source",
            "kind": "text",
            "sample": "test"
          },
          {
            "name": "qualified",
            "kind": "flag",
            "sample": "yes"
          }
        ],
        "rows": 297
      },
      {
        "name": "part_program_usage",
        "columns": [
          {
            "name": "part_no",
            "kind": "text",
            "sample": "VS-ECU-1021-D"
          },
          {
            "name": "program_ref",
            "kind": "text",
            "sample": "PRG-NBX-12"
          },
          {
            "name": "from_sop",
            "kind": "date",
            "sample": "2028-06-24"
          },
          {
            "name": "volume_per_year",
            "kind": "number",
            "sample": "76000"
          }
        ],
        "rows": 228
      },
      {
        "name": "parts",
        "columns": [
          {
            "name": "part_no",
            "kind": "text",
            "sample": "VS-ECU-1021-D"
          },
          {
            "name": "kind",
            "kind": "text",
            "sample": "ecu"
          },
          {
            "name": "name",
            "kind": "text",
            "sample": "ecu 1021"
          },
          {
            "name": "line_id",
            "kind": "text",
            "sample": "PL-DPEPS"
          },
          {
            "name": "lifecycle",
            "kind": "text",
            "sample": "production"
          },
          {
            "name": "make_buy",
            "kind": "text",
            "sample": "buy"
          },
          {
            "name": "supplier_id",
            "kind": "text",
            "sample": "CSUP-06"
          },
          {
            "name": "unit_cost_eur",
            "kind": "number",
            "sample": "98.78"
          },
          {
            "name": "lead_time_days",
            "kind": "number",
            "sample": "52"
          },
          {
            "name": "released_on",
            "kind": "date",
            "sample": "2024-07-02"
          }
        ],
        "rows": 180
      },
      {
        "name": "product_lines",
        "columns": [
          {
            "name": "line_id",
            "kind": "text",
            "sample": "PL-CEPS"
          },
          {
            "name": "architecture",
            "kind": "text",
            "sample": "C-EPS"
          },
          {
            "name": "name",
            "kind": "text",
            "sample": "Vantis Column Assist"
          },
          {
            "name": "force_class_n",
            "kind": "number",
            "sample": "5500"
          },
          {
            "name": "introduced_on",
            "kind": "date",
            "sample": "2011-03-01"
          },
          {
            "name": "status",
            "kind": "text",
            "sample": "current"
          }
        ],
        "rows": 6
      },
      {
        "name": "qualification_tests",
        "columns": [
          {
            "name": "test_id",
            "kind": "text",
            "sample": "QT-2022-0041"
          },
          {
            "name": "part_no",
            "kind": "text",
            "sample": "VS-RACK-2210-A"
          },
          {
            "name": "standard",
            "kind": "text",
            "sample": "internal"
          },
          {
            "name": "attribute",
            "kind": "text",
            "sample": "road_wheel_angle_deg"
          },
          {
            "name": "condition",
            "kind": "text",
            "sample": "end-stop to end-stop, bot…"
          },
          {
            "name": "max_value_demonstrated",
            "kind": "number",
            "sample": "52.000"
          },
          {
            "name": "unit",
            "kind": "text",
            "sample": "deg"
          },
          {
            "name": "result",
            "kind": "text",
            "sample": "pass"
          },
          {
            "name": "tested_on",
            "kind": "date",
            "sample": "2022-01-20"
          },
          {
            "name": "report_ref",
            "kind": "text",
            "sample": "TR-2022-0041"
          }
        ],
        "rows": 210
      }
    ]
  },
  {
    "db": "vst_alm",
    "label": "requirements & architecture",
    "isSystemOfRecord": true,
    "standsFor": "Codebeamer / Polarion / DOORS",
    "tables": [
      {
        "name": "activities",
        "columns": [
          {
            "name": "activity_id",
            "kind": "text",
            "sample": "ACT-ANGLE-SENSE"
          },
          {
            "name": "name",
            "kind": "text",
            "sample": "Steering angle sensing"
          },
          {
            "name": "kind",
            "kind": "text",
            "sample": "monitoring"
          },
          {
            "name": "description",
            "kind": "text",
            "sample": "Acquire absolute steering…"
          }
        ],
        "rows": 12
      },
      {
        "name": "activity_allocations",
        "columns": [
          {
            "name": "activity_id",
            "kind": "text",
            "sample": "ACT-ANGLE-SENSE"
          },
          {
            "name": "element_id",
            "kind": "text",
            "sample": "EL-ALT-08-MECH-05"
          },
          {
            "name": "allocation_type",
            "kind": "text",
            "sample": "primary"
          },
          {
            "name": "rationale",
            "kind": "text"
          }
        ],
        "rows": 317
      },
      {
        "name": "architecture_versions",
        "columns": [
          {
            "name": "arch_id",
            "kind": "text",
            "sample": "ARCH-ALT-08-v1"
          },
          {
            "name": "program_ref",
            "kind": "text",
            "sample": "PRG-ALT-08"
          },
          {
            "name": "version",
            "kind": "number",
            "sample": "1"
          },
          {
            "name": "created_on",
            "kind": "date",
            "sample": "2023-06-11"
          },
          {
            "name": "status",
            "kind": "text",
            "sample": "baselined"
          },
          {
            "name": "supersedes",
            "kind": "text"
          }
        ],
        "rows": 79
      },
      {
        "name": "budget_allocations",
        "columns": [
          {
            "name": "budget_id",
            "kind": "text",
            "sample": "BUD-ALT-08-007"
          },
          {
            "name": "seq",
            "kind": "number",
            "sample": "1"
          },
          {
            "name": "label",
            "kind": "text",
            "sample": "primary path"
          },
          {
            "name": "value",
            "kind": "number",
            "sample": "3.520"
          },
          {
            "name": "basis",
            "kind": "text",
            "sample": "carryover"
          },
          {
            "name": "element_id",
            "kind": "text"
          },
          {
            "name": "child_sr_id",
            "kind": "text"
          }
        ],
        "rows": 66
      },
      {
        "name": "budgets",
        "columns": [
          {
            "name": "budget_id",
            "kind": "text",
            "sample": "BUD-ALT-08-007"
          },
          {
            "name": "parent_sr_id",
            "kind": "text",
            "sample": "SR-ALT-08-0185"
          },
          {
            "name": "program_ref",
            "kind": "text",
            "sample": "PRG-ALT-08"
          },
          {
            "name": "attribute",
            "kind": "text",
            "sample": "on_center_torque_nm"
          },
          {
            "name": "unit",
            "kind": "text",
            "sample": "Nm"
          },
          {
            "name": "target_value",
            "kind": "number",
            "sample": "6.270"
          },
          {
            "name": "operator",
            "kind": "text",
            "sample": "<="
          },
          {
            "name": "tolerance",
            "kind": "number",
            "sample": "0.050"
          },
          {
            "name": "known_open",
            "kind": "flag",
            "sample": "no"
          },
          {
            "name": "closure_note",
            "kind": "text"
          }
        ],
        "rows": 32
      },
      {
        "name": "change_request_items",
        "columns": [
          {
            "name": "chr_id",
            "kind": "text",
            "sample": "CHR-2020-0008"
          },
          {
            "name": "seq",
            "kind": "number",
            "sample": "1"
          },
          {
            "name": "target_kind",
            "kind": "text",
            "sample": "element"
          },
          {
            "name": "target_id",
            "kind": "text",
            "sample": "SR-HLX-H1-0005"
          },
          {
            "name": "action",
            "kind": "text",
            "sample": "delete"
          }
        ],
        "rows": 310
      },
      {
        "name": "change_requests",
        "columns": [
          {
            "name": "chr_id",
            "kind": "text",
            "sample": "CHR-2020-0008"
          },
          {
            "name": "program_ref",
            "kind": "text",
            "sample": "PRG-HLX-H1"
          },
          {
            "name": "raised_on",
            "kind": "date",
            "sample": "2020-12-02"
          },
          {
            "name": "source",
            "kind": "text",
            "sample": "defect"
          },
          {
            "name": "title",
            "kind": "text",
            "sample": "Change to diagnostic set"
          },
          {
            "name": "status",
            "kind": "text",
            "sample": "rejected"
          },
          {
            "name": "decision",
            "kind": "text"
          },
          {
            "name": "decided_on",
            "kind": "date"
          },
          {
            "name": "effort_ref",
            "kind": "text"
          }
        ],
        "rows": 207
      },
      {
        "name": "cr_history",
        "columns": [
          {
            "name": "history_id",
            "kind": "text",
            "sample": "CRH-00002"
          },
          {
            "name": "cr_id",
            "kind": "text",
            "sample": "CR-HLX-H1-0004"
          },
          {
            "name": "changed_on",
            "kind": "date",
            "sample": "2022-08-11"
          },
          {
            "name": "field",
            "kind": "text",
            "sample": "priority"
          },
          {
            "name": "from_value",
            "kind": "text",
            "sample": "53.57"
          },
          {
            "name": "to_value",
            "kind": "text",
            "sample": "49.56"
          },
          {
            "name": "chr_ref",
            "kind": "text"
          },
          {
            "name": "author",
            "kind": "text",
            "sample": "CUS-HLX engineering"
          }
        ],
        "rows": 221
      },
      {
        "name": "customer_requirement_versions",
        "columns": [
          {
            "name": "cr_id",
            "kind": "text",
            "sample": "CR-ALT-08-0129"
          },
          {
            "name": "spec_revision_id",
            "kind": "text",
            "sample": "CRS-ALT-08-001 Rev A"
          },
          {
            "name": "text_body",
            "kind": "text",
            "sample": "The system shall meet roa…"
          },
          {
            "name": "operator",
            "kind": "text",
            "sample": "<="
          },
          {
            "name": "value_num",
            "kind": "number",
            "sample": "48.300"
          },
          {
            "name": "condition",
            "kind": "text"
          },
          {
            "name": "verification_method",
            "kind": "text",
            "sample": "inspection"
          },
          {
            "name": "asil",
            "kind": "text",
            "sample": "D"
          },
          {
            "name": "priority",
            "kind": "text",
            "sample": "must"
          },
          {
            "name": "status",
            "kind": "text",
            "sample": "agreed"
          }
        ],
        "rows": 1273
      },
      {
        "name": "customer_requirements",
        "columns": [
          {
            "name": "cr_id",
            "kind": "text",
            "sample": "CR-ALT-08-0129"
          },
          {
            "name": "spec_id",
            "kind": "text",
            "sample": "CRS-ALT-08-001"
          },
          {
            "name": "section",
            "kind": "text",
            "sample": "4.1.2"
          },
          {
            "name": "title",
            "kind": "text",
            "sample": "road wheel angle deg"
          },
          {
            "name": "attribute",
            "kind": "text",
            "sample": "road_wheel_angle_deg"
          },
          {
            "name": "unit",
            "kind": "text",
            "sample": "deg"
          }
        ],
        "rows": 641
      },
      {
        "name": "elements",
        "columns": [
          {
            "name": "element_id",
            "kind": "text",
            "sample": "EL-ALT-08-ECU-02"
          },
          {
            "name": "arch_id",
            "kind": "text",
            "sample": "ARCH-ALT-08-v1"
          },
          {
            "name": "kind",
            "kind": "text",
            "sample": "ecu"
          },
          {
            "name": "name",
            "kind": "text",
            "sample": "EPS ECU"
          },
          {
            "name": "make_buy",
            "kind": "text",
            "sample": "buy"
          },
          {
            "name": "asil",
            "kind": "text",
            "sample": "D"
          },
          {
            "name": "part_ref",
            "kind": "text"
          },
          {
            "name": "reuse_class",
            "kind": "text",
            "sample": "modified"
          }
        ],
        "rows": 191
      },
      {
        "name": "interfaces",
        "columns": [
          {
            "name": "interface_id",
            "kind": "text",
            "sample": "IF-0001"
          },
          {
            "name": "arch_id",
            "kind": "text",
            "sample": "ARCH-HLX-H1-v1"
          },
          {
            "name": "from_element",
            "kind": "text",
            "sample": "EL-HLX-H1-SENS-01"
          },
          {
            "name": "to_element",
            "kind": "text",
            "sample": "EL-HLX-H1-ECU-02"
          },
          {
            "name": "kind",
            "kind": "text",
            "sample": "analog"
          },
          {
            "name": "signal",
            "kind": "text",
            "sample": "signal"
          },
          {
            "name": "rate_ms",
            "kind": "number",
            "sample": "4.42"
          },
          {
            "name": "asil",
            "kind": "text",
            "sample": "D"
          }
        ],
        "rows": 154
      },
      {
        "name": "spec_documents",
        "columns": [
          {
            "name": "spec_id",
            "kind": "text",
            "sample": "CRS-ALT-08-001"
          },
          {
            "name": "customer_ref",
            "kind": "text",
            "sample": "CUS-ALT"
          },
          {
            "name": "program_ref",
            "kind": "text",
            "sample": "PRG-ALT-08"
          },
          {
            "name": "title",
            "kind": "text",
            "sample": "Calder Electric Power Ste…"
          },
          {
            "name": "kind",
            "kind": "text",
            "sample": "CRS"
          },
          {
            "name": "issued_by",
            "kind": "text",
            "sample": "CUS-ALT engineering"
          }
        ],
        "rows": 38
      },
      {
        "name": "spec_revisions",
        "columns": [
          {
            "name": "spec_revision_id",
            "kind": "text",
            "sample": "CRS-ALT-08-001 Rev A"
          },
          {
            "name": "spec_id",
            "kind": "text",
            "sample": "CRS-ALT-08-001"
          },
          {
            "name": "revision",
            "kind": "text",
            "sample": "Rev A"
          },
          {
            "name": "received_on",
            "kind": "date",
            "sample": "2020-01-28"
          },
          {
            "name": "effective_from",
            "kind": "date",
            "sample": "2020-01-28"
          },
          {
            "name": "effective_to",
            "kind": "date",
            "sample": "2020-05-27"
          },
          {
            "name": "change_note",
            "kind": "text",
            "sample": "Initial issue for quotati…"
          },
          {
            "name": "supersedes",
            "kind": "text"
          }
        ],
        "rows": 76
      },
      {
        "name": "system_requirement_versions",
        "columns": [
          {
            "name": "sr_id",
            "kind": "text",
            "sample": "SR-ALT-08-0181"
          },
          {
            "name": "revision",
            "kind": "number",
            "sample": "1"
          },
          {
            "name": "effective_from",
            "kind": "date",
            "sample": "2025-03-17"
          },
          {
            "name": "effective_to",
            "kind": "date",
            "sample": "2026-03-31"
          },
          {
            "name": "text_body",
            "kind": "text",
            "sample": "The system shall achieve …"
          },
          {
            "name": "operator",
            "kind": "text",
            "sample": ">="
          },
          {
            "name": "value_num",
            "kind": "number",
            "sample": "9.670"
          },
          {
            "name": "condition",
            "kind": "text"
          },
          {
            "name": "verification_method",
            "kind": "text",
            "sample": "analysis"
          },
          {
            "name": "asil",
            "kind": "text",
            "sample": "QM"
          },
          {
            "name": "status",
            "kind": "text",
            "sample": "superseded"
          },
          {
            "name": "maturity",
            "kind": "text",
            "sample": "specified"
          }
        ],
        "rows": 1321
      },
      {
        "name": "system_requirements",
        "columns": [
          {
            "name": "sr_id",
            "kind": "text",
            "sample": "SR-ALT-08-0181"
          },
          {
            "name": "program_ref",
            "kind": "text",
            "sample": "PRG-ALT-08"
          },
          {
            "name": "title",
            "kind": "text",
            "sample": "assist latency ms"
          },
          {
            "name": "attribute",
            "kind": "text",
            "sample": "assist_latency_ms"
          },
          {
            "name": "unit",
            "kind": "text",
            "sample": "ms"
          },
          {
            "name": "owner_discipline",
            "kind": "text",
            "sample": "hardware"
          },
          {
            "name": "derivation_note",
            "kind": "text",
            "sample": "Derived from the customer…"
          }
        ],
        "rows": 888
      },
      {
        "name": "trace_cr_sr",
        "columns": [
          {
            "name": "cr_id",
            "kind": "text",
            "sample": "CR-ALT-08-0129"
          },
          {
            "name": "sr_id",
            "kind": "text",
            "sample": "SR-ALT-08-0184"
          },
          {
            "name": "coverage",
            "kind": "text",
            "sample": "full"
          },
          {
            "name": "rationale",
            "kind": "text"
          }
        ],
        "rows": 1291
      },
      {
        "name": "trace_sr_element",
        "columns": [
          {
            "name": "sr_id",
            "kind": "text",
            "sample": "SR-ALT-08-0181"
          },
          {
            "name": "element_id",
            "kind": "text",
            "sample": "EL-ALT-08-ECU-02"
          },
          {
            "name": "rationale",
            "kind": "text"
          }
        ],
        "rows": 1327
      }
    ]
  },
  {
    "db": "vst_pmo",
    "label": "effort & cost actuals",
    "isSystemOfRecord": true,
    "standsFor": "SAP / Clarity",
    "tables": [
      {
        "name": "effort_by_discipline",
        "columns": [
          {
            "name": "effort_id",
            "kind": "text",
            "sample": "EFF-2021-0443"
          },
          {
            "name": "discipline",
            "kind": "text",
            "sample": "hardware"
          },
          {
            "name": "hours",
            "kind": "number",
            "sample": "1908.0"
          }
        ],
        "rows": 2078
      },
      {
        "name": "effort_records",
        "columns": [
          {
            "name": "effort_id",
            "kind": "text",
            "sample": "EFF-2021-0443"
          },
          {
            "name": "chr_ref",
            "kind": "text"
          },
          {
            "name": "program_ref",
            "kind": "text",
            "sample": "PRG-HLX-H1"
          },
          {
            "name": "title",
            "kind": "text",
            "sample": "Gearbox housing change, H…"
          },
          {
            "name": "completed_on",
            "kind": "date",
            "sample": "2021-11-26"
          },
          {
            "name": "change_class",
            "kind": "text",
            "sample": "modify_hardware"
          },
          {
            "name": "element_kind",
            "kind": "text",
            "sample": "gearbox"
          },
          {
            "name": "asil",
            "kind": "text",
            "sample": "B"
          },
          {
            "name": "reuse_class",
            "kind": "text",
            "sample": "modified"
          },
          {
            "name": "interfaces_touched",
            "kind": "number",
            "sample": "1"
          },
          {
            "name": "safety_case_impact",
            "kind": "flag",
            "sample": "no"
          },
          {
            "name": "tooling_required",
            "kind": "flag",
            "sample": "yes"
          },
          {
            "name": "actual_hours",
            "kind": "number",
            "sample": "3180.0"
          },
          {
            "name": "calendar_weeks",
            "kind": "number",
            "sample": "71"
          },
          {
            "name": "region",
            "kind": "text",
            "sample": "EU"
          },
          {
            "name": "year",
            "kind": "number",
            "sample": "2021"
          },
          {
            "name": "outcome_note",
            "kind": "text",
            "sample": "Booked against this chang…"
          }
        ],
        "rows": 640
      },
      {
        "name": "quote_lines",
        "columns": [
          {
            "name": "quote_id",
            "kind": "text",
            "sample": "QUO-0001"
          },
          {
            "name": "seq",
            "kind": "number",
            "sample": "1"
          },
          {
            "name": "description",
            "kind": "text",
            "sample": "new function on K2"
          },
          {
            "name": "change_class",
            "kind": "text",
            "sample": "new_function"
          },
          {
            "name": "hours",
            "kind": "number",
            "sample": "1998.0"
          },
          {
            "name": "cr_ref",
            "kind": "text"
          }
        ],
        "rows": 301
      },
      {
        "name": "quotes",
        "columns": [
          {
            "name": "quote_id",
            "kind": "text",
            "sample": "QUO-0001"
          },
          {
            "name": "rfq_ref",
            "kind": "text",
            "sample": "RFQ-2026-0044"
          },
          {
            "name": "program_ref",
            "kind": "text",
            "sample": "PRG-KST-K2"
          },
          {
            "name": "issued_on",
            "kind": "date",
            "sample": "2026-09-25"
          },
          {
            "name": "quoted_hours",
            "kind": "number",
            "sample": "2409.0"
          },
          {
            "name": "quoted_eur",
            "kind": "number",
            "sample": "226446.00"
          },
          {
            "name": "tooling_eur",
            "kind": "number"
          },
          {
            "name": "outcome",
            "kind": "text",
            "sample": "open"
          },
          {
            "name": "actual_hours_final",
            "kind": "number"
          }
        ],
        "rows": 52
      },
      {
        "name": "rate_cards",
        "columns": [
          {
            "name": "year",
            "kind": "number",
            "sample": "2019"
          },
          {
            "name": "region",
            "kind": "text",
            "sample": "CN"
          },
          {
            "name": "discipline",
            "kind": "text",
            "sample": "calibration"
          },
          {
            "name": "rate_eur_per_hour",
            "kind": "number",
            "sample": "53.32"
          }
        ],
        "rows": 168
      }
    ]
  },
  {
    "db": "vst_derived",
    "label": "What we derived from the files",
    "isSystemOfRecord": false,
    "standsFor": "ours, not theirs — built by pnpm derived:parse",
    "tables": [
      {
        "name": "derived_effort",
        "columns": [
          {
            "name": "effort_id",
            "kind": "text",
            "sample": "EFF-2021-0443"
          },
          {
            "name": "file_id",
            "kind": "text",
            "sample": "pmo/closure-reports/EFF-2…"
          },
          {
            "name": "change_class",
            "kind": "text",
            "sample": "modify_hardware"
          },
          {
            "name": "element_kind",
            "kind": "text",
            "sample": "gearbox"
          },
          {
            "name": "asil",
            "kind": "text"
          },
          {
            "name": "safety_case_impact",
            "kind": "flag",
            "sample": "no"
          },
          {
            "name": "tooling_required",
            "kind": "flag",
            "sample": "yes"
          },
          {
            "name": "interfaces_touched",
            "kind": "number",
            "sample": "1"
          },
          {
            "name": "reported_hours",
            "kind": "number",
            "sample": "3180.0"
          },
          {
            "name": "calendar_weeks",
            "kind": "number",
            "sample": "71"
          },
          {
            "name": "booked_hours",
            "kind": "number",
            "sample": "3180.0"
          }
        ],
        "rows": 220
      },
      {
        "name": "document_chunks",
        "columns": [
          {
            "name": "id",
            "kind": "text",
            "sample": "00013d15-1cec-4129-99e4-7…"
          },
          {
            "name": "content",
            "kind": "text",
            "sample": "Quotation QUO-0004 > Post…"
          },
          {
            "name": "metadata",
            "kind": "json",
            "sample": "[object Object]"
          },
          {
            "name": "vector",
            "kind": "other"
          },
          {
            "name": "content_ts",
            "kind": "other",
            "sample": "'-0004':3 '-07':13 '-18':…"
          }
        ],
        "rows": 2827
      },
      {
        "name": "document_fields",
        "columns": [
          {
            "name": "file_id",
            "kind": "text",
            "sample": "pmo/closure-reports/EFF-2…"
          },
          {
            "name": "line_no",
            "kind": "number",
            "sample": "4"
          },
          {
            "name": "field",
            "kind": "text",
            "sample": "reference"
          },
          {
            "name": "label_raw",
            "kind": "text",
            "sample": "Reference"
          },
          {
            "name": "value",
            "kind": "text",
            "sample": "EFF-2021-0443"
          }
        ],
        "rows": 2060
      },
      {
        "name": "effort_split_lines",
        "columns": [
          {
            "name": "file_id",
            "kind": "text",
            "sample": "pmo/closure-reports/EFF-2…"
          },
          {
            "name": "line_no",
            "kind": "number",
            "sample": "27"
          },
          {
            "name": "subject",
            "kind": "text",
            "sample": "EFF-2021-0443"
          },
          {
            "name": "discipline",
            "kind": "text",
            "sample": "hardware"
          },
          {
            "name": "hours",
            "kind": "number",
            "sample": "1908.0"
          }
        ],
        "rows": 695
      },
      {
        "name": "effort_totals",
        "columns": [
          {
            "name": "file_id",
            "kind": "text",
            "sample": "pmo/closure-reports/EFF-2…"
          },
          {
            "name": "subject",
            "kind": "text",
            "sample": "EFF-2021-0443"
          },
          {
            "name": "hours",
            "kind": "number",
            "sample": "3180.0"
          },
          {
            "name": "weeks",
            "kind": "number",
            "sample": "71"
          }
        ],
        "rows": 220
      },
      {
        "name": "estimate_lines",
        "columns": [
          {
            "name": "file_id",
            "kind": "text",
            "sample": "pmo/estimates/PRG-ALT-08-…"
          },
          {
            "name": "line_no",
            "kind": "number",
            "sample": "5"
          },
          {
            "name": "program_ref",
            "kind": "text",
            "sample": "PRG-ALT-08"
          },
          {
            "name": "author",
            "kind": "text",
            "sample": "I. Arnaud"
          },
          {
            "name": "estimated_on",
            "kind": "date",
            "sample": "2024-01-23"
          },
          {
            "name": "work_package",
            "kind": "text",
            "sample": "EOL calibration"
          },
          {
            "name": "discipline",
            "kind": "text",
            "sample": "validation"
          },
          {
            "name": "hours",
            "kind": "number",
            "sample": "143.0"
          },
          {
            "name": "basis",
            "kind": "text",
            "sample": "supplier quote"
          },
          {
            "name": "confidence",
            "kind": "text",
            "sample": "medium"
          }
        ],
        "rows": 287
      },
      {
        "name": "extracted_facts",
        "columns": [
          {
            "name": "file_id",
            "kind": "text",
            "sample": "pmo/closure-reports/EFF-2…"
          },
          {
            "name": "subject",
            "kind": "text",
            "sample": "EFF-2021-0443"
          },
          {
            "name": "field",
            "kind": "text",
            "sample": "asil"
          },
          {
            "name": "value",
            "kind": "text"
          },
          {
            "name": "evidence",
            "kind": "text"
          },
          {
            "name": "evidence_line",
            "kind": "number"
          },
          {
            "name": "evidence_exact",
            "kind": "flag",
            "sample": "yes"
          },
          {
            "name": "model",
            "kind": "text",
            "sample": "gpt-5-mini"
          },
          {
            "name": "extracted_at",
            "kind": "date",
            "sample": "2026-09-13"
          }
        ],
        "rows": 1318
      },
      {
        "name": "quote_line_items",
        "columns": [
          {
            "name": "file_id",
            "kind": "text",
            "sample": "pmo/quotes/QUO-0001.md"
          },
          {
            "name": "line_no",
            "kind": "number",
            "sample": "9"
          },
          {
            "name": "quote_id",
            "kind": "text",
            "sample": "QUO-0001"
          },
          {
            "name": "seq",
            "kind": "number",
            "sample": "1"
          },
          {
            "name": "description",
            "kind": "text",
            "sample": "new function on K2"
          },
          {
            "name": "change_class",
            "kind": "text",
            "sample": "new_function"
          },
          {
            "name": "hours",
            "kind": "number",
            "sample": "1998.0"
          }
        ],
        "rows": 301
      },
      {
        "name": "rate_card_lines",
        "columns": [
          {
            "name": "file_id",
            "kind": "text",
            "sample": "pmo/rate-cards/2019-CN.csv"
          },
          {
            "name": "line_no",
            "kind": "number",
            "sample": "6"
          },
          {
            "name": "year",
            "kind": "number",
            "sample": "2019"
          },
          {
            "name": "region",
            "kind": "text",
            "sample": "CN"
          },
          {
            "name": "discipline",
            "kind": "text",
            "sample": "systems"
          },
          {
            "name": "rate_eur_per_hour",
            "kind": "number",
            "sample": "59.52"
          }
        ],
        "rows": 168
      },
      {
        "name": "rejected_facts",
        "columns": [
          {
            "name": "file_id",
            "kind": "text",
            "sample": "pmo/closure-reports/EFF-B…"
          },
          {
            "name": "field",
            "kind": "text",
            "sample": "change_class"
          },
          {
            "name": "value",
            "kind": "text",
            "sample": "integration_only"
          },
          {
            "name": "evidence",
            "kind": "text",
            "sample": "integration only \n\n  inte…"
          },
          {
            "name": "reason",
            "kind": "text",
            "sample": "the quoted sentence is no…"
          },
          {
            "name": "model",
            "kind": "text",
            "sample": "gpt-5-mini"
          }
        ],
        "rows": 2
      },
      {
        "name": "source_files",
        "columns": [
          {
            "name": "file_id",
            "kind": "text",
            "sample": "pmo/closure-reports/EFF-2…"
          },
          {
            "name": "kind",
            "kind": "text",
            "sample": "closure-report"
          },
          {
            "name": "sha256",
            "kind": "text",
            "sample": "1dd7c9168db90c1b589564624…"
          },
          {
            "name": "bytes",
            "kind": "number",
            "sample": "1169"
          },
          {
            "name": "lines",
            "kind": "number",
            "sample": "42"
          },
          {
            "name": "ingested_at",
            "kind": "date",
            "sample": "2026-09-13"
          }
        ],
        "rows": 355
      },
      {
        "name": "timesheet_lines",
        "columns": [
          {
            "name": "line_id",
            "kind": "number",
            "sample": "1"
          },
          {
            "name": "file_id",
            "kind": "text",
            "sample": "pmo/timesheets/2019-Q4.csv"
          },
          {
            "name": "line_no",
            "kind": "number",
            "sample": "6"
          },
          {
            "name": "week_ending",
            "kind": "date",
            "sample": "2019-10-01"
          },
          {
            "name": "employee_raw",
            "kind": "text",
            "sample": "P. Strand"
          },
          {
            "name": "charge_code_raw",
            "kind": "text",
            "sample": "1041"
          },
          {
            "name": "charge_code_key",
            "kind": "text",
            "sample": "1041"
          },
          {
            "name": "hours",
            "kind": "number",
            "sample": "15.0"
          },
          {
            "name": "activity",
            "kind": "text",
            "sample": "hardware"
          },
          {
            "name": "approved",
            "kind": "flag",
            "sample": "yes"
          },
          {
            "name": "note",
            "kind": "text"
          }
        ],
        "rows": 10688
      }
    ]
  }
];

/** Every `<db>.<table>`. `estate-notes.ts` must cover all of them. */
export type EstateTableKey =
  | 'vst_crm.contacts'
  | 'vst_crm.customers'
  | 'vst_crm.milestones'
  | 'vst_crm.programs'
  | 'vst_crm.rfq_specs'
  | 'vst_crm.rfqs'
  | 'vst_plm.assemblies'
  | 'vst_plm.bom_lines'
  | 'vst_plm.component_suppliers'
  | 'vst_plm.part_capabilities'
  | 'vst_plm.part_program_usage'
  | 'vst_plm.parts'
  | 'vst_plm.product_lines'
  | 'vst_plm.qualification_tests'
  | 'vst_alm.activities'
  | 'vst_alm.activity_allocations'
  | 'vst_alm.architecture_versions'
  | 'vst_alm.budget_allocations'
  | 'vst_alm.budgets'
  | 'vst_alm.change_request_items'
  | 'vst_alm.change_requests'
  | 'vst_alm.cr_history'
  | 'vst_alm.customer_requirement_versions'
  | 'vst_alm.customer_requirements'
  | 'vst_alm.elements'
  | 'vst_alm.interfaces'
  | 'vst_alm.spec_documents'
  | 'vst_alm.spec_revisions'
  | 'vst_alm.system_requirement_versions'
  | 'vst_alm.system_requirements'
  | 'vst_alm.trace_cr_sr'
  | 'vst_alm.trace_sr_element'
  | 'vst_pmo.effort_by_discipline'
  | 'vst_pmo.effort_records'
  | 'vst_pmo.quote_lines'
  | 'vst_pmo.quotes'
  | 'vst_pmo.rate_cards'
  | 'vst_derived.derived_effort'
  | 'vst_derived.document_chunks'
  | 'vst_derived.document_fields'
  | 'vst_derived.effort_split_lines'
  | 'vst_derived.effort_totals'
  | 'vst_derived.estimate_lines'
  | 'vst_derived.extracted_facts'
  | 'vst_derived.quote_line_items'
  | 'vst_derived.rate_card_lines'
  | 'vst_derived.rejected_facts'
  | 'vst_derived.source_files'
  | 'vst_derived.timesheet_lines';
